### ISSUE TITLE
Hub: data-bound sections empty when navigating to the same page twice

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1007]
I have a listview on my fragment page:

```
<section aria-label="Main content" role="main">
      <div class="hub lists" data-win-control="WinJS.UI.Hub" data-win-bind="winControl.sections:lists">
      </div>
</section>
```

The pages JS does this:

```
WinJS.UI.Pages.define("/pages/data.html", {
  lists: new WinJS.Binding.List(),

  init: function(element, options) {
    return this.loader = app.requestAsync("/data/" + options.id);
  },

  processed: function(element, options) {
    var self = this;
    return WinJS.Binding.processAll(element, this).then(function() {
      return self.loader;
    }).then((function(data) {
        self.lists.splice(0, self.lists.length);
        return data.lists.forEach(function(list, index) {
          var items, section;
          section = WinJS.Utilities.isPhone ? new WinJS.UI.PivotItem() : new WinJS.UI.HubSection();
          section.header = list.name;
          items = new WinJS.Binding.List();
          WinJS.UI.Fragments.renderCopy("/pages/_list.html", section.contentElement).then(function(element) {
            return WinJS.UI.processAll(section.contentElement);
          }).then(function(contentElement) {
            return contentElement.querySelector(".itemList").winControl.itemDataSource = items.dataSource;
          });
          self.lists.push(section);
        });
    });
  }
```

When the page is loaded the first time, the hub sections are correctly created. Navigating to the page again (without navigating to another page inbetween) renders an empty hub with empty sections:

![image](https://cloud.githubusercontent.com/assets/164625/6895256/a62e2f2e-d6de-11e4-8aec-75d25928034a.png)

I've set breakpoint into the Hubs iteminserted event listeners for its sections property, and those are called.

**Comment by rigdern** [comment]
@jseanxu See if there's enough information to repro the bug.

**Comment by jseanxu** [comment]
@pke 
I can't repro this issue. I created an app with a PageControl with a single page that has a hub and it uses pretty much the same lifecycle implementations as in your code above, minus the loader stuff. I load another page thru Fragment.renderCopy that has a ListView that binds to some global data. The ListView renders on repeated navigation to this same page for me.

Try trimming down your app and see if your data is getting lost in between navigations. Since there is no exceptions in your case, and the Hub's data mutation events fire as you said, I believe that this might be an app issue.

**Comment by jseanxu** [comment]
Closing this - open another one or respond here if this is still an issue.

**Comment by pke** [comment]
The bug appears in my "trello MX" prototype. When you switch quickly between boards.
https://github.com/pke/trellomx

**Comment by jseanxu** [comment]
Could you provide a more reduced repro?
