### ISSUE TITLE
Let WinJS.UI.SettingsFlyout.populateSettings support external href URIs

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1009]
According to [Kraig's Blogpost](http://www.kraigbrockschmidt.com/2013/03/13/mixing-links-flyouts-settings-winjs/) about WinJS application settings flyout handling WinJS does not support `href` to point to external URLs.

Why is that? Would you accept a pull-request to fix this behaviour so that we can easily link to external "Privacy Policy" sites?

**Comment by rigdern** [comment]
I'm not familiar with the history around why `populateSettings` does not support external URLs.

Note that SettingsFlyout is being deprecated in WinJS 4. The reasoning for the deprecation is that in Win10 the UI design has changed such that we recommend having a settings page rather than putting settings into a flyout.

**Comment by pke** [comment]
About the new design in Windows 10. Currently the settings pane also holds the permissions and package infos. Where are those suppose to go in new Windows 10 apps. And are we really back to hide app settings in each apps menus again?

**Comment by jseanxu** [comment]
Let's consolidate this discussion to #1219.
