### ISSUE TITLE
Repeater not binding correctly in Internet explorer

### ISSUE THREAD

**Issue by ThatsIT** [winjs/winjs#1033]
I have a repeater example where I have binded to a select, I chrome I can bind a selected attribute, but in IE it shows as selected=""
http://jsfiddle.net/zvyydugo/

**Comment by TheWrathOfConst** [comment]
This was an interesting bug. Turns out that the root cause for this problem is browser specific, and both Firefox and IE are getting this wrong (but in different ways).

This is a simplified version of what the WinJS template code actually does to render the option elements in this repeater:

```html
    <button onclick="createSelectControl()">Create select control</button>
    <script>
        function createSelectControl() {
            var selectControl = document.createElement("select");
            for (var i = 0; i < 5; i++) {
                var temporarySelectControl = document.createElement("select");
                var optionHTML = "<option " + (i === 3 ? "selected" : "") + ">" + "Item " + i + "</option>";
                temporarySelectControl.insertAdjacentHTML("beforeend", optionHTML);
                selectControl.appendChild(temporarySelectControl.firstElementChild);
            }
            document.body.appendChild(selectControl);
        }
    </script>
```

I've hardcoded this example to create 5 options and always select the fourth item. In our template code, each option gets rendered into a temporary select element, and gets moved to its final destination in the repeater code. This example mimics that behavior by creating a temporary select control for each option to be rendered in, renders the option element, then immediately moves the rendered option element to the real select element.

This code snippet works in IE and Chrome, but Firefox doesn't handle this correctly.

IE's issue is a little more interesting. Here is an expanded version of that same repro:
```html
    <button onclick="createSelectControl(false)">Create select control</button>
    <button onclick="createSelectControl(true)">Create select control, query for an undefined property</button>
    <script>
        function createSelectControl(checkForUndefinedProperty) {
            var selectControl = document.createElement("select");
            for (var i = 0; i < 5; i++) {
                var temporarySelectControl = document.createElement("select");
                var optionHTML = "<option " + (i === 3 ? "selected" : "") + ">" + "Item " + i + "</option>";
                temporarySelectControl.insertAdjacentHTML("beforeend", optionHTML);
                if (checkForUndefinedProperty) {
                    console.log(temporarySelectControl.thisPropertyDoesNotExist); // Querying for an undefined property makes the wrong option end up selected!
                }
                selectControl.appendChild(temporarySelectControl.firstElementChild);
            }
            document.body.appendChild(selectControl);
        }
    </script>
```

It's the same code, but with this little bit added in:
```js
                if (checkForUndefinedProperty) {
                    console.log(temporarySelectControl.thisPropertyDoesNotExist); // Querying for an undefined property makes the wrong option end up selected!
                }
```
The code is the same, but before it moves the option element into the final select control, it has the option to check for a property that doesn't exist on the temporary select control. If we try to get this property, the select control that gets rendered to the page will have Item 4 selected instead of Item 3!

I'll open bugs on the browsers for these issues.
