### ISSUE TITLE
WinJS.Binding.List: change sorting condition after re-order in sorted projection

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1039]
I have a sorted projection that is sorted by the items "pos" property.
The listview is has `listView.itemsReorderable=true` and I have a listener on the projections base list when on `itemmoved` to update the items `pos` parameter.

But it seems this interferes with the sorted projection somehow, that also watches for `itemmoved` events. The effect is that the item is not moved in the list, but stays at its old position. A breakpoint in the sorted projections sort function is not hit, after my ìtemmoved` handler changed the items `pos`.

I have the following setup:

```
baseCardsList = new WinJS.Binding.List();
filteredCardsList = baseCardsList.createFiltered(function(card) {
  return !card.closed;
});
cards = filteredCardsList.createSorted(function(a, b) {
  return a.pos - b.pos;
});
baseCardsList.addEventListener("itemmoved", function(event) {
  var card, nextPos, prevPos;
  card = event.detail.value;
  if (event.detail.newIndex === 0) {
    card.pos = 0.0;
  } else {
    if (event.detail.newIndex === cards.length - 1) {
      nextPos = 0x7fffffff;
    } else {
      nextPos = cards.getAt(event.detail.newIndex + 1).pos;
    }
    prevPos = cards.getAt(event.detail.newIndex - 1).pos;
    card.pos = 0.5 * (nextPos + prevPos);
  }  
});
```

Do I need to listen for the ´itemmoved` event on another of those lists?

**Comment by TheWrathOfConst** [comment]
Is the ListView in this scenario using baseCardsList or filteredCardsList as its datasource?

**Comment by pke** [comment]
Its using the `cards` itemlist

**Comment by TheWrathOfConst** [comment]
The problem is that the ListView is trying to mutate your sorted projection. It's best to avoid mutating projections, since the behavior is best described as "non-intuitive". The original designer of projections was on the fence about making projections mutable at all.

It's probably safer and easier for you to implement the move on the baseCardsList yourself. The ListView fires the events `itemdragstart` when a drag starts (you'll use this to determine what item index is being dragged), and `itemdragdrop` when a reorder is being completed. The `itemdragdrop` event can be canceled, which will give you the opportunity to handle the move yourself by getting the original item in the base list, changing its pos, and calling notifyMutated on the base list. 

I wrote a quick prototype of this solution (inserting my own fake data + listview for testing purposes), and it seems to work:

```js
        var data = [];
        for (var x = 0; x < 10; x++) {
            data.push({ pos: (10 - x), closed: (x % 2 === 0), });
        }
        baseCardsList = new WinJS.Binding.List(data);
        filteredCardsList = baseCardsList.createFiltered(function (card) {
            return !card.closed;
        });
        cards = filteredCardsList.createSorted(function (a, b) {
            return a.pos - b.pos;
        });

        var draggedItemIndex;
        var lv = new WinJS.UI.ListView(null, { itemDataSource: cards.dataSource, itemsReorderable: true });
        lv.addEventListener("itemdragstart", function (e) {
            draggedItemIndex = e.detail.dragInfo.getIndices()[0]; // This only uses the first index, but you can extend this to support multiple items being dragged
        });
        lv.addEventListener("itemdragdrop", function (e) {
            var movedItemKey = cards.getItem(draggedItemIndex).key;
            var newLocation = e.detail.insertAfterIndex; // Note: Can be -1, which denotes that the item should be inserted at index 0
            var prevItemPos = (newLocation > -1 ? cards.getAt(newLocation).pos : 0);
            var nextItemPos = (newLocation < cards.length - 1 ? cards.getAt(newLocation + 1).pos : 0x7fffffff);           

            var movedCard = baseCardsList.getItemFromKey(movedItemKey);
            movedCard.data.pos = (prevItemPos + nextItemPos) / 2;
            baseCardsList.notifyMutated(baseCardsList.indexOfKey(movedItemKey));

            e.preventDefault();
        });
        document.body.appendChild(lv.element);
```
