### ISSUE TITLE
In UAP platform, WInJS flyout control is not fitting well in smaller form factors - for PCs and tablets it adjusts upto certain extent, but in smaller devices such as phones it is not rendering well.  This prevents the usage of this control in UAP

### ISSUE THREAD

**Issue by mikewjackson** [winjs/winjs#1056]
In UAP platform, WInJS flip view control is not fitting well in smaller form factors - for PCs and tablets it adjusts upto certain extent, but in smaller devices such as phones it is not rendering well. This prevents the usage of this control in UAP, and requires a lot of custom adjustment and code.

**Comment by mikewjackson** [comment]
the comment above about the flipview control is misleading. It should all relate to the flyout control

**Comment by AmazingJaze** [comment]
Flyouts and Menu's have a max width of 456px defined in style redlines. This is makes full width flyouts and menu's too wide and they clip off the edge of the window since so many phones that are 480 physical pixels wide apply a zoom factor bringing them closer to 320px virtual pixels.

The solution here is to use a media query to make the flyouts and menu's have max-width: 100vw when the media width is less than 456px
