### ISSUE TITLE
Appbar responds to IHM incorrectly on Windows Phone platform.

### ISSUE THREAD

**Issue by darkyen** [winjs/winjs#1060]
In WinJS 2.x when running on windows phone the appbar hovers over the keyboard or at the bottom of the screen, while doing the same in WinJS 4.0 it appears at the bottom of the viewport which is left after keyboard pops open. (and also obsecures the text-field). 

Is this intentional change ?
Can there be some platform specific code by which I can re-enable the old behavior ?

**Comment by AmazingJaze** [comment]
Hi @darkyen can you provide a screenshot of the behavior you are seeing?

**Comment by AmazingJaze** [comment]
Note, that in WinJS 2.x for WP 8.1 the WinJS AppBar was rendered as a system level component that was exposed through the WinRT instead of the WinJS 2.x for Windows 8.1 HTML AppBar control. 

We now use the HTML AppBar on every platform, including Win 10 WWA Universal Apps and it is not possible to render HTML AppBar below the virtual keyboard on the Windows Phone app platform. 

Trying this myself today, It appears that one of the WinRT API's that the WinJS AppBar has historically used to re-position itself when the Keyboard shows has not been converged to the Phone platform, and the AppBar is being positioned incorrectly because of it. 

This is something that we will need a solution for in Win 10 Universal Apps. I will follow up internally with the team who owns these APIs.

**Comment by darkyen** [comment]
Wait so we cannot write apps for win 8 with winjs 4.0 ? (yet)

-----Original Message-----

**Comment by AmazingJaze** [comment]
@darkyen  Yes, you are able to write apps for Windows 8.x with WinJS 4.0. With that being said, WinJS 4.0 has been designed and built for Windows 10. This upcoming major release introduces a new design language, numerous feature improvements, and a handful of breaking changes. Thus, while technically possible, we do not recommend your app target Windows 8.x when using WinJS 4.0 once the tools to target Windows 10 have been released later this year.

**Comment by darkyen** [comment]
Great, We were actually trying to build something which works on windows 8 to 10 giving a native-ish feeling throughout and also supports android / iOS. I ended up making the choice of WinJS and Flux for that instance, for windows < 8.1 now we use winjs 2.1 and all other platforms use winjs 4.0.0-preview, sorry about absence i am uploading the screenshots to you asap.
