### ISSUE TITLE
Why does data-win-res not handle nested properties like data-win-bind?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1063]
Its really confusing to have the different formatting styles for Resources and Binding.

`data-win-bind="winControl.label:label"`
-vs- 
`data-win-res="{ winControl: { label:'label' } }"`

What's the technical reason for that?
Nicer and less verbose would be: 
`data-win-res="{'winControl.label':'label'}"`
Even better, let us omit the curly braces.

**Comment by AmazingJaze** [comment]
@pke 

Just to clarify, in you last code snippet did you mean to write
` data-win-res="{'winControl.label':'label'}" `  
instead of 
` data-win-bind="{'winControl.label':'label'}" `  ?

I wasn't around during the design phase of these features, but after looking at your question some more I wonder if originally, data-win-bind, data-win-options and data-win-res were all meant to be used by the same parser, but then data-win-bind needed to be updated to accept a 3rd parameter as a binding initializer, and it wasn't easy to represent that in the JSON format, so it needed to be updated to its current form?

I'm marking this as a feature request for future consideration, but you can always talk to us about sending a pull request if this is something you would like to contribute to the platform and have available in a quicker time frame.

**Comment by AmazingJaze** [comment]
Edited original response inline.

**Comment by pke** [comment]
> Just to clarify, in you last code snippet did you mean to write
data-win-res="{'winControl.label':'label'}"

Yes, good catch. I have updated the original post.

Your reasoning for the `data-win-bind` makes sense. Still the `data-win-res` syntax could be simplified and it would be less error prone. Because at the moment I make this mistake often, to use the `data-win-bind` syntax and it does not print out any errors to the log if a resource string is not found, or does it?

**Comment by rigdern** [comment]
We extracted the following feature requests from this issue:
  1. Use `WinJS.log` to emit an error when attempting to use `data-win-res` with a resource string that doesn't exist.
  2. Make the `data-win-res` syntax the same as the `data-win-bind` syntax. If we did this, would we also have to update the `data-win-options` syntax?

**Comment by jayrenn** [comment]
I have added the two requests to our internal tracking.

**Comment by pke** [comment]
just one question @jayrenn about this "internal tracking" you mentioned on some of the closed bugs/requests. How do we know this feature request is completed if this here is closed and added to your internal tracking? Will it ever resurface from your internal tracking? What's wrong about tracking it openly here, accepting pull-request and close it when the feature is completed?

**Comment by jayrenn** [comment]
Fair question. Tracking the feature requests on GitHub is certainly a viable option, and one we took in the past. However, we have decided that, for our purposes, it is much easier to consolidate all our work items into one tool. Since we use internal tools for tracking dev tasks, etc., it made sense to migrate the feature requests there to avoid duplication and keep them on our radar. I'll be sure to update the feature requests on GitHub as they are completed in order to notify the requester and interested parties. I'll also reference the issue # in our release notes.
