### ISSUE TITLE
ToolBar should size to content

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1083]
ToolBar by default should size its width to its content and only overflow its content when an absolute width or maxWidth is set. Maybe it could have a default maxWidth of 100%.

Since this control isn't supposed to be app-wide, it can be used in scenarios where the toolbar isn't supposed to be full-width.

**Comment by AmazingJaze** [comment]
ToolBar is optimized today to cache all widths of its children and not read from the DOM except when it absolutely has to in order to avoid layout costs.

We would have to re think some of these strategies to make it size to content and still overflow commands correctly when it can no longer get any bigger. 

Specifically, we don't know when the CSS for a width or max width has been applied. There fore if someone applies it and then adds a command via the binding list, we would have to re measure everything and read our CSS from the DOM to see if we should size to content, or overflow.

For the time being I think we are going to stick to the requirement that the ToolBar and The AppBar should both either have a fixed width: e.g. `width: 400px' or a width based on the width of an ancestor element: `width: 35%`, and should never have a display property such as inline, inline-block, or inline-flex that would cause it to size to content.  

I have already sent similar comments to our doc writing team to cover these intricacies and more.

**Comment by jayrenn** [comment]
Added to internal tracking.
