### ISSUE TITLE
Press-and-hold on ListView items doesn't bring up context menu

### ISSUE THREAD

**Issue by derek1ee** [winjs/winjs#1090]
**Repro**
1. Use ListView at http://try.buildwinjs.com/#listviewinteractions
2. Make sure you can right-click with mouse to open context menu 
3. Press-and-hold on the same item, and observe behavior

**Expected**
Context menu shows up when press-and-hold

**Actual**
No context menu shows up when press-and-hold

**Comment by TheWrathOfConst** [comment]
This behavior is by design. The ListView has always prevented the context menu from appearing on items. Here's the comment regarding this behavior from our code:

```
                // In order for the control to play nicely with other UI controls such as the app bar, it calls preventDefault on
                // contextmenu events. It does this only when selection is enabled, the event occurred on or within an item, and
                // the event did not occur on an interactive element.
                onContextMenu: function ItemEventsHandler_onContextMenu(eventObject) {
                    var containerElement = this._site.containerFromElement(eventObject.target);

                    if (this._selectionAllowed() && containerElement && !this._isInteractive(eventObject.target)) {
                        eventObject.preventDefault();
                    }
                },
```

**Comment by derek1ee** [comment]
Press-and-hold and right-click should behave the **same way**. Currently, right-click shows context menu, regardless of select mode, but press-and-hold doesn't not.

**Comment by phosphoer** [comment]
What platform are you seeing this behavior on? I'm unable to repro the context menu displaying on click with select modes other than ReadOnly in Chrome, IE11, and Spartan.

**Comment by TheWrathOfConst** [comment]
I was able to repro this behavior. Sure enough, right click will pop up a context menu, but press-and-hold doesn't. Interestingly enough, the `ItemEventsHandler_onContextMenu` event handler isn't even being called when this happens.

**Comment by TheWrathOfConst** [comment]
Looks like the reason the context menu never appears in IE on touch is we also have an event handler for `onMSHoldVisual`, which calls preventDefault() under more circumstances than our context menu event handler:

```js
                onMSHoldVisual: function ItemEventsHandler_onMSHoldVisual(eventObject) {
                    if (!this._isInteractive(eventObject.target)) {
                        eventObject.preventDefault();
                    }
                },
```

I went through the source history to see what the reasoning behind this was. Back in 2012 the thinking was that press&hold should never display a context menu under any circumstances. If I remember right, that's because the model we were pushing at the time said that there shouldn't be any P&H interactions ever (cross slide and context-aware appbars were supposed to be used instead), and so we built that limitation directly into the ListView.

I think it's worth re-evaluating this decision now that cross slide's gone. At a bare minimum I think it's reasonable to get this MSHoldVisual event handler to block context menus under the same circumstances as our onContextMenu event handler. I think we also might want to look into also removing the code to block context menu when selection is enabled. It was reasonable to block context menu on right clicks in a selectable listview in Win8 because right click could select items. Right click doesn't select anymore, so many context menus should work again?
