### ISSUE TITLE
SplitView: paneHidden == undefined defaults to visible

### ISSUE THREAD

**Issue by limefrogyank** [winjs/winjs#1111]
When you databind the paneHidden property of a SplitView, if the control is initialized before the viewmodel's default values are set, then the paneHidden property gets an undefined value.  This causes the pane to animate into view.  This is problematic when you want it to default to hidden.  You will end up with the pane animating twice: once visible for the undefined value and again hidden for the databind value of true being initialized in the viewmodel.

I realize this is an artifact of the MVVM setup I am using, but it seems that the SplitView should at least default to hidden status when the paneHidden property receives an undefined value, since that is the starting state of the control.  In my own case, I fixed this behavior by attaching a converter that interprets an undefined value as "true".

using: WinJS.4.0 4.0.0.winjs.2015.3.18 WinJS.js
same as on try.buildwinjs.com page

**Comment by rigdern** [comment]
Thanks for the feedback. That's a very good point!

We've actually renamed the SplitView's `paneHidden` property to `paneOpened` because we think the open/close terminology better describes the SplitView's behavior than the show/hide terminology.

This renaming happens to also fix your scenario. Because `paneOpened` treats `undefined` as `false`, setting `paneOpened` to `undefined` will result in a closed SplitView pane.

**Comment by limefrogyank** [comment]
Seems like that would close this issue then... thanks!

**Comment by dlemon** [comment]
Try WinJS site still talks about paneHidden property. Where can I find the correct API, or should I browse the code?

**Comment by rigdern** [comment]
`paneHidden` the property in WinJS 4.0.0-preview

`paneOpened` is the property in master and WinJS 4.0.0 (to be released shortly)

**Comment by dlemon** [comment]
Thanks!
