### ISSUE TITLE
WinJS.Binding: binding converter not called for 'undefined' values?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1118]
I have this markup:
`<div data-win-bind="style.display:src app.binding.displayIf">Source: <span data-win-bind="textContent:src"></span></div>`

and my converter function `app.binding.displayIf` is not called if `src` is undefined. Is this intentional or a bug?
Its defined as 

```
WinJS.Namespace.define("app.binding", {
  displayIf: WinJS.Binding.converter(function (value) {
    return value ? "block" : "none";
  })
});
```

**Comment by jseanxu** [comment]
I am unable to repro this issue, I created a simple test page and my custom initializer gets called just fine. Here is the code I'm using:

```html
<body>
    <div data-win-bind="textContent: Data.foo Data.myInit"></div>
    <script>
        window.Data = {
            myInit: WinJS.Binding.initializer(function (src, srcProp, dest, destProp) {
                debugger;
            })
        }
        WinJS.Utilities.markSupportedForProcessing(window.Data);
        WinJS.Binding.processAll();
    </script>
</body>
```

Running this under the debugger should break you in the initializer function.

**Comment by pke** [comment]
Sorry, forgot to mention that I am using a converter, not initializer function. And the converter is not called with undefined values.

**Comment by jseanxu** [comment]
Oh, this is indeed a bug, great catch :)!

For now, there is a simple workaround - you could set the value to be bound to `null`.

**Comment by jseanxu** [comment]
Notes regarding the cause of the bug:

In the `initializerOneBinding` function in `declarative.js`, we try to consume an undocumented and unused 5th parameter called `initialValue` which is always `undefined` as far as I can tell. Before calling the specified converter, we check whether the value-to-be-bound is the same as `initialValue` and skip calling the converter if that is true. Since `initialValue` is always `undefined`, this check will evaluate to true if the binding value is indeed `undefined`.

This check should be removed since there is a realistic scenario for a developer to converter `undefined` to something more customer friendly.

**Comment by pke** [comment]
> Oh, this is indeed a bug, great catch :)!

hehe. I find them all. I have still not given up on using WinJS in production apps ;)

> For now, there is a simple workaround - you could set the value to be bound to null.

That's what I am doing atm, but as you explained in your second comment `undefined` is a realistic value to have that should not go into the UI unconverted.
