### ISSUE TITLE
WinJS.Menu needs updated Animation

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1147]
Win 10 introduces new animations for Menu's. WinJS Menu animations needs to be updated to reflect these changes.

WinJS has always used the same animations for Menus and Flyouts. We recently added an implementation for cascading menu’s and flyouts, all of our current animations for hiding and showing can be seen on these pages:
http://winjs-jessesh.azurewebsites.net/CascadingMenu/
http://winjs-jessesh.azurewebsites.net/Flyouttestpage/

I have sent internal mail to @alxlu and @nizh914 to try and verify whether or not Flyout animations in Win10 were updated as well.

**Comment by omnoms** [comment]
I hope the "feature" that it closes the flyout on a toggle button is just simply because it's tied to the same function that closes it enmasse without taking those things into consideration... would be horrible if I had placed 10 toggle buttons (i.e. settings) and the user would have to reopen nested flyouts for every toggle :)
