### ISSUE TITLE
Cannot wire 'secondary' app bar command 

### ISSUE THREAD

**Issue by appeality** [winjs/winjs#1196]
I am able to wire 'primary' appbar commands OK. However, when attempting to wire 'secondary' commands, they are never invoked.

<button data-win-control="WinJS.UI.AppBarCommand" data-win-options="{id:'cmdMyFavorites',label:'My Favorites',icon:'emoji',tooltip:'My Favorites',section:'secondary'}"></button>

JS
var cmdViewFavs = document.getElementById('cmdMyFavorites');
cmdViewFavs.addEventListener("click", function(){
console.log('cmdViewFavs clicked!');
});

**Comment by AmazingJaze** [comment]
Hi @appeality 
From your description it sounds like you may be hitting #841 ? 
This has been fixed in the master branch and will be included in the official release of WinJS 4.0. 
If you include the latest WinJS from master does it resolve your issue?

Assuming this is #841, ff you need a workaround until the next stable version of WinJS is released you can call AppBar.forceLayout() anytime you update a property on any secondary commands to force the update to take hold.

**Comment by AmazingJaze** [comment]
Actually looking at it some more, it appears this is an issue where you are trying to hook up the event listener to the element directly rather than the AppBarCommand object. Normally this would work just fine with any manner of WinJS controls, and as you've seen it even works with primary commands however:

Whether its secondary commands, or primary commands that overflow due to a lack of space in the action area, the elements that get rendered into the AppBar overflowarea are just HTML projections and not the actual elements associated with the AppBarCommands.

This means that any event listeners added through the addEventListener API, get stored on the initial HTML element associated with the AppBar Command and not the proxy element that is used to represent them when they appear in the overflow area. 

The correct way to handle this would be to use the AppBarCommand object's onclick property to set the event handler. You should be able to do this as simply as:

```js
var cmdViewFavs = document.getElementById('cmdMyFavorites');
cmdViewFavs.winControl.onclick = ("click", function(){
   console.log('cmdViewFavs clicked!');
});
```
Previously bug #841 would have prevented this from working as well. Please let us know if this resolves your issue.

**Comment by appeality** [comment]
Thanks, I will try this.
