### ISSUE TITLE
Box Sizing Issue

### ISSUE THREAD

**Issue by RichiCoder1** [winjs/winjs#1218]
I ran into an issue where, after introducing the Auto Suggest Box, the suggestions were too small. After a bit of diagnosing, I found out that it was because WinJS assumes `box-sizing` to be `content-box` for the suggestions, and my reset css sets `border-box` globally. I don't imagine I'm alone in this default as a number of larger CSS frameworks do that recently. WinJS should either explicitly set the `box-sizing` of controls that depend on that behavior, or warn users of this potential pitfall.

**Comment by jseanxu** [comment]
Hi @RichiCoder1 

Thanks for identifying this issue. I believe this issue is a symptom of a larger issue that is user styles leaking into and overriding framework styles. While this particular issue could be resolved by explicitly styling the `box-sizing` to `border-box`, I suspect that this type of issue will be seen elsewhere depending on what inheritable styles you put on the body.
For example, if you were to style all `div` elements on your page to have a default `margin` or `padding` then you would see adverse effects of this in many different controls. It is therefore unfeasible to explicitly set every single style on every element inside a control.

Out of curiosity, which larger CSS frameworks behave this way?

**Comment by RichiCoder1** [comment]
The most immediate one that I'm aware of it [bootstrap](http://getbootstrap.com/getting-started/#third-box-sizing), as well as [Semantic UI](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/globals/reset.less#L25). Bootstrap specifically caused issues for me. And the `html { box-sizing: border-box; } * { box-sizing: inherit }` seems to be very popular advice.

**Comment by jayrenn** [comment]
Thanks for the feedback! I have added this request to our internal tracking.
