### ISSUE TITLE
Flyouts hit crash when constructed with option hidden: false

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#1233]
Repro:
```js
var flyout = new WinJS.UI.Flyout(null, {anchor: document.body, hidden: false});
```

**Comment by AmazingJaze** [comment]
This appears to have been introduced when we made the hidden property get/set.

**Comment by AmazingJaze** [comment]
The problem is 2 fold
1) The flyout requires and anchor property in order to be shown with the hidden:false property. Even if an anchor element is also passed to the constructor, setOptions might still try and set hidden:false first, which will cause the Flyout to throw a custom "Anchor not found" exception.
2) The flyout uses the _LightDismissService now, which requires notifiying the Flyout._dismissable property whenever the flyout is shown. We don't instantiate the _dismissable object until the end of the constructor after we have already set options, so trying to set hidden:false through the constructor will trigger a null exception in the flyout.show() code path,  where we are trying to call a method on the _dismissable object before if has been instantiated.
