### ISSUE TITLE
Try site does not render any samples in Firefox

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#1251]
Every sample throws these script errors:

no element found
`TypeError: c.getComputedStyle(...) is null`

**Comment by rigdern** [comment]
Fixed the Try Site. Details on the bug are below.

In Firefox, `getComputedStyle` returns null within an iframe which is `display:none`. This appears to be against the speced behavior which states that `getComputedStyle` always returns a `CSSStyleDeclaration`:
  - [CSS spec](http://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-ViewCSS)
  - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)

There's a Firefox issue from 2010 tracking this: https://bugzilla.mozilla.org/show_bug.cgi?id=548397

This Firefox bug affects [this line](https://github.com/winjs/winjs/blob/8f7e215fab216f079bf19aecc798438986a5cb80/src/js/WinJS/_Accents.ts#L154) of the Accent color code which runs during WinJS's initialization. This line was throwing an exception on the Try Site preventing any of the samples from rendering in the inline viewer. The fix was to use `visibility:hidden`
