### ISSUE TITLE
Infinite loop from VirtualizedDataSource.

### ISSUE THREAD

**Issue by darkyen** [winjs/winjs#1279]
For some reason the VirtualizedDataSource queries starts querying for data indefinitely

The following is my implementation (uses es6).
```javascript

function Range(topLimit){
   return Array.apply(null, Array(500)).map(function (_, i) {return i;})
}

class SampleDataAdapter{
   constructor(database, queryOptions){
    this._queryOptions = queryOptions;
    this._data = Range(500).map(el => { return {
      displayName: 'Element Number ' + el
    }});
  } 

  itemsFromIndex(requestIndex, countBefore, countAfter){
    console.log("Querying for", requestIndex, countBefore, countAfter);
    let limit  = (countAfter + countBefore) + 1;
    let offset = requestIndex - countBefore;
    
    return Promise.resolve({
      offset: offset,
      items: this._data.slice(offset, limit).map( (element, idx) => { return {
        key: (idx + offset).toString(),
        data: element
      }}),
      totalCount: this._data.length
    })

    getCount(){
       return Promise.resolve(this._data.length);
    }
}      
```

At a random index after scrolling the VirtualizedDataSource starts querying this indefinitely
and the logs are 

```
..
Querying for 53 1 14
Querying for 0 0 0
Querying for 53 1 14
Querying for 0 0 0
Querying for 53 1 14
..
```

**Comment by rigdern** [comment]
I see a couple of problems in the posted code:
  - The `end` parameter of `slice` isn't correct. It should be `offset + limit` instead of `limit`. Like this:

  ```js
  this._data.slice(offset, offset + limit)
  ```

  - The `offset` in the return value of `itemsFromIndex` isn't correct. As described in the [`IFetchResult.offset`](https://msdn.microsoft.com/en-us/library/windows/apps/br212549.aspx) documentation, it should be the index of `requestIndex` within the `items` array. Which would make the correct value of `offset` `countBefore`. Like this:

  ```js
  return Promise.resolve({
      offset: countBefore,
      items: ...
      totalCount: this._data.length
  })
  ```

You can learn about creating VirtualizedDataSources from the WinJS docs:
  - [Tutorial](https://msdn.microsoft.com/en-us/library/windows/apps/hh770849.aspx)
  - [Sample code](https://code.msdn.microsoft.com/ListView-custom-data-4dcfb128/sourcecode?fileId=50893&pathId=1036163654)

**Comment by darkyen** [comment]
Oh I though from the bingImageSource example that the offset literally meant offset of returned dataset. Sorry for the bad call.
