### ISSUE TITLE
AppBarCommand  id parameter is not passed into the .onclick event

### ISSUE THREAD

**Issue by dimkir** [winjs/winjs#1283]
AppBarCommand `id` parameter is not passed into `.onclick`event for AppBarCommands which are in "secondary" section. 

To reproduce the problem add one line to the first appbar-sample from http://try.buildwinjs.com/#appbar:create 

Under `var msg = ...`  add line:
```javascript
msg += " command.id='" + command.id + "' and command.winControl.id='" + command.winControl.id + "'";
```
So it looks like this:
![image](https://cloud.githubusercontent.com/assets/3438798/8511579/73192754-2316-11e5-9d8b-a8f3e0c55d9f.png)

Now If I go back to the "Output" tab and click on any of the appbar "primary" command (eg. "remove"), I would get all the expected parameters including the `id` = `cmdRemove`:
![image](https://cloud.githubusercontent.com/assets/3438798/8511613/5fe88b32-2318-11e5-8b0a-b6755c7d6fa3.png)

However if you press any of the "secondary" commands, eg. "Print", you would get other parameters (eg. `.label` or `.tooltip`), but `id` would be empty:
![image](https://cloud.githubusercontent.com/assets/3438798/8511609/2e5e628a-2318-11e5-988f-e5a5eba1b908.png)

This seems to persist in latest 4.0.1, it also seems to persist in Chrome and IE11 and also on Windows Phone 8.1.

Also in WinJS 2.1 this was working fine.

HTH

**Comment by AmazingJaze** [comment]
Hi dimkir, thanks for the bug. This is caused by a limitation in our current 4.X implementation of the AppBar. When Commands appear in the overflow area, we are using a separate WinJS.UI.MenuCommand with its own separate element and winControl to represent the original AppBarCommand element.  In this case we weren't passing the id through because it would result in two commands in the DOM having the same id which could lead to all sort of other confusing problems that would likely confuse developers.

The complete fix for this bug feels like it would require an expensive refactoring and will need to be triaged against other high priority bugs. In the mean time, is there a particular scenario that is blocked by this bug where you require a work around?
