### ISSUE TITLE
Protractor: Regression in WinJS - test case "WinJSTests.FlipperInstantiationTests: NoNavigationOnResize " in "winjs/bin/tests/FlipView/test.html"

### ISSUE THREAD

**Issue by mikewjackson** [winjs/winjs#1310]
Test case "WinJSTests.FlipperInstantiationTests: NoNavigationOnResize " in "winjs/bin/tests/FlipView/test.html" failed in the latest Protractor run. Protractor determined that this failure is a regression from mshtml or a previous build of edgehtml (based on historical data). Please investigate why this test has begun failing.

**Comment by mikewjackson** [comment]
This is a result of a resize and scroll event occurring in close proximity. However, we believe this issue will be addressed by removing the mselementresize event handler as tracked by #1308

**Comment by rigdern** [comment]
### Repro Steps

The test failure is due to a race condition which triggers intermittently. It requires Edge to repro the bug. The test only fails sometimes so I did some work to make it easier to repro. I uploaded a subset of the FlipView tests from the WinJS repository to OneDrive (link in the repro steps). Having a subset of the tests makes it easier to repro because the tests are run thru several iterations before the bug triggers. Repeating the 1 failing test alone doesn't trigger the bug.

1. Download and unzip `repro.zip` from http://1drv.ms/1DwCmSO
2. Open a Windows command prompt in the repro directory
3. Run `npm install`
4. Run `grunt connect:localhost`
5. In Edge, open `http://localhost:9666/bin/tests/FlipView/test.html?fastanimations=true&loop=true`
6. Click the "Start" button

After several iterations, `WinJSTests.FlipperInstantiationTests: NoNavigationOnResize ` will fail with an exception:

![image](https://cloud.githubusercontent.com/assets/199935/9148677/44246dee-3d3a-11e5-85b4-57f953ecc2db.png)
