### ISSUE TITLE
Integrating with AMD Loaders

### ISSUE THREAD

**Issue by olearydw** [winjs/winjs#1325]
Docs indicate that winjs can be used with other 3d party libraries like jQuery and Dojo.  Modern dojo leverages AMD.  Need docs or sample to understand best approach to integrate AMD lib with winjs.  Specifically where to place dojo init and require statements within the winjs lifecycle to avoid conflicts.

**Comment by rigdern** [comment]
@olearydw I'm not familiar with Dojo and I'm not aware of any problems between jQuery, AMD, and WinJS. Here are some questions for you so we can better assist you:
  1. Are you able to use WinJS with AMD or would you like some assistance with that? If you need assistance, what problems have you run into? Can you provide a minimal repro?
  2. Have you run into any problems with using jQuery with WinJS? If yes, can you provide a minimal repro? If not, what are your concerns about using jQuery with WinJS?
  3. Same questions as (2) except for Dojo instead of jQuery.
