### ISSUE TITLE
ListView within Pivot control does not display when binding itemDataSource manually

### ISSUE THREAD

**Issue by nguyenhthai** [winjs/winjs#1327]
Using the 4.1 version of WinJS, I have encountered an issue where a ListView that is placed inside of a PivotItem does not render after binding the itemDataSource of the ListView manually. For example, under a PivotItem, I have a ListView that only declare the data-win-control attribute and no data-win-options like **itemDataSource** or **itemTemplate**. Within the code, I create a data list and bind that list to the ListView. However, when starting up, the ListView does not render all the items. To solve this, I have either triggering manually the **forceLayout()** for the ListView after loading or using timer to trigger that. The **forceLayout()** is already called when I did the binding before. This was not happened when I developed my app using version 4.0 Preview.

Below is an example:
HTML:

    <div class="messageTemplate" data-win-control="WinJS.Binding.Template">
        <div class="message">
            <div class="messageContent">
                <div class="contactInformation">
                    <div class="contactName" data-win-bind="textContent: name"></div>
                    <div class="contactTime" data-win-bind="textContent: time"></div>
                </div>
            </div>
        </div>
    </div>
    
    <div id="messageList" data-win-control="WinJS.UI.Pivot">
        <div class="pivotItem" data-win-control="WinJS.UI.PivotItem" data-win-options="{ 'header': 'Test' }">
            <div id="testListView" data-win-control="WinJS.UI.ListView"></div>
        </div>
    </div>

JS:

    (function () {
        "use strict";
        var important = new WinJS.Binding.List([
            { name: "Test1", time: "4:44p" },
            { name: "Test2", time: "12:53p" },
            { name: "Test3", time: "10:32a" }
        ]);

        WinJS.Namespace.define("Sample", {
            Important: important,
            initializeListView: function () {
                var listView = document.querySelector("#testListView").winControl;
                listView.itemDataSource = Sample.Important.dataSource;
                var listViewTemplate = document.querySelector(".messageTemplate");
                listView.itemTemplate = listViewTemplate;
                listView.layout = new WinJS.UI.ListLayout();
                listView.forceLayout();
            }
        });

        WinJS.UI.Pages.define("./pages/login/login.html", {
            ready: function (element, options) {
                 Sample.initializeListView();  // This will not render the ListView during the startup
                 // Either wait and then initialize or manually trigger forceLayout() after the Pivot is loaded
                 setTimeout(function() {
                     Sample.initializeListView();  // Worked
                 }, 1000);
            }
        });
    })();

**Comment by toddpi314** [comment]
@nguyenhthai IMO, the fix for this is to make the list view aware of parent pivots and call reflows on item init.

To retrofit your code for this now:
1. Go ahead and bind your datasource on ready in the pivot item sub-view
2. Monitor the "itemanimationend' on the pivot
3. On first animate of the pivot item, walk the DOM for data-win-controls that contain the forceLayout method and call

Notice: 
- You are responsible for tracking if a pivot item has been loaded or not; just track in a global collection, since after first animate, the standard item datasource change notifications will update correctly
- This approach starts at the pivot. The ListView can also be updated to be aware of parent DOM items and monitor itself within a pivot.

Hope that helps!

**Comment by Dvbnhbq** [comment]
Have the same issue. When ready function is called, no pivot items has been rendered at all. It doesn't matter what controls are the children of the pivot items, they are not ready when page ready function is called. In my opinion, this is an issue.

**Comment by vajnorcan** [comment]
I'm having the same problem plus the listview doesn't render all the item. The listview does render at the first time, only at the second time its pivot's been navigated. Interestingly, this doesn't seem to be a problem with v4.0 or something that I've used for my WP8.1 app. 
Also, please notice 
 - that once you navigate to the second item multiple times, the listview is always of the different height.
 - not all the items are rendered

Attached is the very simple test case. -> https://www.dropbox.com/sh/rvbhl4nurk457ix/AABSkfznfDFHbqqd3ynrzn5ta?dl=0

**Comment by nguyenhthai** [comment]
Currently, in order to work around this problem, I used **itemanimationstart** event to force the layout update at the first time the PivotItem is loaded. If you have many pivot items, this approach is not a good idea since you have to force update every single one of the pivot items. Keep in mind that you also want to force update only at the first time since the animation for **forceLayout** function will kicked and everytime users swipe the pivot, that would be the animation that users see.

**Comment by vajnorcan** [comment]
I can also report that on IE10 and Edge it works all good. Chrome is showing all signs mentioned here

**Comment by AmazingJaze** [comment]
@vajnorcan @toddpi314 @nguyenhthai 

The discrepancies between IE, Edge and Chrome may be that ListView and a handful of other WinJS controls (ViewBox, Pivot, Hub, FlipView, SemanticZoom, NavBarContainer)  register for the "mselementresize" event to detect when their root element has changed size,. When a resize is detected these controls will typically fire forceLayout() or some optimized private implementation of it to re layout themselves in response to size changes.

Because of the "ms" vendor prefix name, this doesn't scale to other browsers and up until WinJS 4.3 the only fallback in place was to manually call forceLayout yourself.

As of this month, I have replaced the dependency on mselementresize in our master branch with a browser agnostic purely event driven JavaScript solution that is based around this blog post from back alley coder: http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/ 

The decision to do this work was motivated by the announcement that Edge would be removing the "mselementresize" event in a future update. My change will be included in WinJS 4.4 later this month.

This has appeared to much more closely normalize the behavior of reflowing based on element resize across all of our supported browsers. However, that is not to say that the we have completely recreated the exact same behaviors as "mselementresize" in all browsers, or even in Edge & IE11. Specifically, there are some tangential scenarios where a control that was listening for element resize and then had its display set to none, or was re-parented somewhere else in the DOM, where our new implementation is sometimes better and sometimes worse at detecting resize than "mselementresize" itself.

But I do believe the new implementation to be much more consistent across all browsers an particularly flawless in scenarios where a ListView control with % based height and width, is nested inside of some other element or control that resizes itself. 

With the new change, the ListView should automatically detect the resize and re layout itself in all supported browsers not just IE and Edge.

Please keep a look out for this change in WinJS 4.4 and let us know if this helps mitigate some of the pain here.  

If there are any places where you were calling forceLayout manually to handle element resize, I would be interested to know which if any of those are still necessary after this change goes live.

**Comment by AmazingJaze** [comment]
Updated above comment inline

**Comment by vajnorcan** [comment]
great work, will keep an eye on it, as it's been quite a pain to figure out why it all works fine on one platform and not on the other. Also, I have noticed that sizing and layouting is also picky otherway around, that is it works flawlessly on chrome and other browsers, but not in IE. But for now I'd wait for the new release and test on that one.
Again, thanks for your time and response. cheers

**Comment by Guadzilah** [comment]
Okay great

**Comment by Guadzilah** [comment]
Okay great

**Comment by Guadzilah** [comment]
sales configuration

**Comment by Guadzilah** [comment]
okay

**Comment by Adriaanse** [comment]
Not sure why this issue was closed as i am still having this issue with chrome and WinJS release 4.4.1 ?

I) found a very good solution: 
1) add and "onselectionchanged" event handler to the pivot menu.
2) in the event handler, set "event.detail.item._element.style.display = "";" and the problem is solved.
