### ISSUE TITLE
tasks/options/github-release.js prevents grunt build

### ISSUE THREAD

**Issue by syslogic** [winjs/winjs#1328]
it just didn't want to build, then tried with `grunt -v`
(cannot scroll back that far to paste the initial error message).

after removing that github-release.js task, it built instantly.

**Comment by jdalton** [comment]
@rigdern could you sanity check this. I gave it a quick look and couldn't find anything glaring.

**Comment by rigdern** [comment]
My guess is that the problem is due to [this line](https://github.com/winjs/winjs/blob/c95741ce1930f11ca04a5eb13940f6db6a27d935/tasks/options/github-release.js#L8) which runs a git command to get the current commit hash.

We should change the task so it only runs that code if the user runs the `publish` task. However, the commit hash is needed as a grunt option and I know of no way to compute this option on demand -- it seems to be needed at task configuration time. Assuming this is the problem, I can think of 2 solutions:
  1. Fork `grunt-github-releaser` and add the ability to compute the commit hash on demand by allowing it to be specified as a function which will be called when the value is needed.
  2. Instead of publishing to GitHub by configuring a grunt task (`grunt-github-releaser`), rewrite the automation to publish to GitHub using imperative APIs.
