### ISSUE TITLE
AppBarCommand can not set alignment from left to right in Universal Windows Application 

### ISSUE THREAD

**Issue by PatrickSCLin** [winjs/winjs#1437]
can not set AppBarCommand alignment from left to right in Universal Windows project,

any ideas ?

**Comment by jdalton** [comment]
Hey @PatrickSCLin! What version of WinJS are you using and what version of Windows are you targeting?

**Comment by PatrickSCLin** [comment]
I was using WinJS 4.0, target is Windows 10, it's an universal windows project,

I can set 'selection' or 'global' to let alignment of AppBarCommand be LTR or RTL but it only work on Windows 8.1 Universal Project,

How to archive this on Windows 10 Universal Project with WinJS 4.0 ?

**Comment by AmazingJaze** [comment]
Hi @PatrickSCLin the design for AppBar in Windows 10 has been modified a great deal since Windows 8.1 and has moved away from the RTL and LTR designation of commands.

The AppBarCommand section property now supports "primary" and "secondary" and those values designate whether a command should appear in the AppBar's actionarea or overflowarea. "secondary" commands will only ever appear in the overflowarea whereas primary commands will appear in the actionarea as long as there is enough room, any excess of 'primary' command that can't fit will overflow into the overflowarea until more space becomes available in the actionarea.

The "selection" and "global" values for the section api have been deprecated and today are both treated as "primary" commands.

You can check out these articles to learn more about the new features and design of the AppBar and ToolBar controls:

https://msdn.microsoft.com/en-us/library/windows/apps/hh465296.aspx
https://msdn.microsoft.com/en-us/library/windows/apps/hh465309.aspx

The primary difference between a ToolBar and AppBar is that the AppBar is always an overlay and can only be positioned at the bottom or the top edge of the App window. It will always cover other content in the App canvas while visible. The ToolBar can be placed anywhere in your App but will exist on the same plane as your content while closed and won't overlay.

The AppBar has the restriction that it should always be an immediate child of the <body> element in order to guarantee that it can always function correctly, but the ToolBar does not have that restriction, however it does come with a few CSS styling restrictions as a tradeoff: 
https://msdn.microsoft.com/en-us/library/windows/apps/jj839733.aspx

Here are a couple of test pages I have been using for the ToolBar and AppBar. The page will load slowly because its hosted on a free account.
http://winjs-jessesh.azurewebsites.net/appbar/index.html
http://winjs-jessesh.azurewebsites.net/toolbar/index.html

And in the dropdown on this page are some published samples of some interesting new ToolBar and command properties that all apply to the AppBar and AppBarCommand as well.
http://try.buildwinjs.com/playground/

Let me know if I can answer any more questions.

**Comment by AmazingJaze** [comment]
Additionally you can check out the [change log](https://github.com/winjs/winjs/wiki/Changelog) on our wiki for the full breadth of AppBar changes starting with WinJS 4.0
