### ISSUE TITLE
Press and Hold an item inside a Listview, couldn't get the srcElement from "contextmenu" event handler

### ISSUE THREAD

**Issue by hanshi7** [winjs/winjs#1442]
1. Create a sample with ListView.
2. Add event handler for contextmenu event:
            var listView = element.querySelector('#basicListView').winControl;
            function itemInvokedHandler(event) {
            }
            listView.addEventListener("contextmenu", itemInvokedHandler, false);
3. set a break point inside the itemInvokedHandler.

Observed the event.srcElement is different between right-click and press and hold.
For right-click, the event.srcElement is the item that gets clicked.
However, for press and hold, the event.srcElement is the "_win-proxy" element of the ListView.

The impact of this bug is that for press and hold event, it is not possible to bring up the correct context menu for the item being press-hold because we cannot get the item.

**Comment by rigdern** [comment]
@hanshi7 This is because the ListView [sets pointer capture](https://github.com/winjs/winjs/blob/0850f3e84ba41f4af059de1d94433176ae309eea/src/js/WinJS/Controls/ItemContainer/_ItemEventsHandler.js#L138) for touch events.

Can you use `document.elementFromPoint` to figure out which item the interaction took place within based on the coordinates of the event? (for example something like `document.elementFromPoint(eventObject.clientX, eventObject.clientY);`)
