### ISSUE TITLE
MediaPlayer - Controls should be at a higher z-index

### ISSUE THREAD

**Issue by ghost** [winjs/winjs#1449]
Partners will create edge to edge overlays when content is finished.  Currently if you create an overlay, the controls are not clickable.  It looks like a z-index (z-index: 1003?) should be added to the CSS class .win-mediaplayer-doublerow .win-mediaplayer-transportcontrols at line 4471 in ui-dark.css in the srinivasdandu/MediaPlayer branch.  This allows the auto-hide / unhide on the media player controls to still be invokable over an edge to edge / top to bottom overlay added by a third-party developer.

**Comment by RobCamer** [comment]
OK, I just noticed that when you put the media player controls at a different z-index, the controls cover 100% of the screen, so there must be an alternative on how to create an overlay with the control?

**Comment by RobCamer** [comment]
More inf---I don’t mean “full screen” mode.  I mean 100% of the window area.

So, I have an overlay that covers the entire window.  It works great, however, when the mediaplayer controls unhide, they are not clickable because the MediaPlayer controls are “under” my 100% height / width overlay.  

OK, so I thought I’d try to change the z-order on just the media player controls with this CSS:

.win-mediaplayer-doublerow .win-mediaplayer-transportcontrols {
              z-index: 1003;
}

Now when the video plays to the end and I get my custom post-roll overlay, the MediaPlayer controls are invokable, however, now my custom overlay UI is not invokable because the MediaPlayer controls also take up 100% of the height and width of the window.  

Ideally, the MediaPlayer controls do not take up the entire window and instead just occupy the space where the controls are.  Also, partners are going to want to customize the built-in overlay anyway so there needs to be a way to override it.  

Screen capture to hopefully help:
App is running windowed

**Red box** in the below image is my custom overlay with a 20% black and the Queue information displayed.  It is 100% height / width of the window normally but I shortened it to 92vh so that I could click the controls underneath, which is why the media player controls look half darker on the top.  

**Green** box in the below image is the built-in overlay that’s a part of the MediaPlayer control.  How can a developer override or otherwise disable that?  

**Orange box** in the below image is the area I expected the mediaplayer controls to take up after I adjusted the z-order to 1003 for the controls, but when I set the z-index on the mediaplayer controls to 1003 to put the controls “over” my custom overlay, the mediaplayer control appears to cover 100% of the height / width of the window.

<img width="1217" alt="mediaplayeroverlay" src="https://cloud.githubusercontent.com/assets/10854024/9947334/58c1de42-5d67-11e5-8dff-e08f3129e66a.png">
