### ISSUE TITLE
MediaPlayer: Command tooltips don't show up

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1463]
1. Download and unzip `repro.zip` from http://1drv.ms/1Qo5YTB
2. Open a command line in the `repro` folder and run:
  - `npm install`
  - `npm start`
3. Open `http://localhost:8080/` in Chrome
4. In the Chrome console, run this command to ensure that the controls don't hide: `mp._showControls(false, true);`
5. Hover the mouse over one of the MediaPlayer's controls

**Expected result:** A tooltip shows up

**Actual result:** No tooltip shows up

**Comment by rigdern** [comment]
This bug is caused by a heuristic around tooltips that is built into the `AppBarCommand`. The tooltip is not shown if all of these conditions are met:
  1. Command's tooltip is identical to its label
  2. Command is within a non-reduced `AppBar`. This is a heuristic which is supposed to mean "the Command's label is shown". However, this is stale code and we don't even have reduced vs non-reduced `AppBar`'s anymore.

Relevant code:
  - [Compares label and tooltip](https://github.com/winjs/winjs/blob/8e8a3b0621fe9f3acd7f815d7e961136c2f220fa/src/js/WinJS/Controls/AppBar/_Command.js#L556-L558)
  - [Closes tooltip](https://github.com/winjs/winjs/blob/8e8a3b0621fe9f3acd7f815d7e961136c2f220fa/src/js/WinJS/Controls/AppBar/_Command.js#L635-L638) if all of the conditions mentioned earlier are met.

### Possible Solutions

You might think we can just update `heuristic (2)` to be based on `closedDisplayMode`s instead of reduced vs non-reduced. However, this won't help `MediaPlayer` because it uses `closedDisplayMode: full` (labels are shown by default) and then manually hides the labels. It wants this `closedDisplayMode` because it only wants the invoke button (`...` button) to show if there are actually commands that overflowed.

Because the `MediaPlayer` doesn't want to render its labels, you might think it should just leave the labels blank. However, this will likely break accessibility because the labels get used for the `aria-label`.

Options:
  1. `MediaPlayer` is updated to leave the labels blank. `AppBarCommand` is updated to use the tooltip as its `aria-label` if no `label` is provided.
    - Downside: It might make the `AppBarCommand`'s code a little more complicated.
  2. Completely get rid of the `AppBarComand`'s tooltip hiding heuristic. The consumer specified both the `label` and the `tooltip`. If they didn't want a tooltip because it was identical to the `label`, they shouldn't have specified a `tooltip`.
    - `Downside:` If the developer switches their `AppBar` from `closedDisplayMode:compact` to `closedDisplayMode:full`, it could be annoying to update all of the `tooltip`s to be empty string. (this is assuming that we fix `heuristic (2)` to care about `closedDisplayMode`s instead of reduced vs non-reduced.)

What do you think, @AmazingJaze?

**Comment by AmazingJaze** [comment]
The labels also get used if commands overflow into the overflow area, so while the MediaPlayer is manually hiding them via CSS in the action area, they need to have set the label property and they have to not hide it it when the command gets overflown since there are no icons to otherwise identify the commands there.

In the case of the AppBarCommands, I wonder if we can change it to always show the tooltip if they were set explicitly. I believe that if the AppBar.tooltip property was set, then the AppBarCommand will use the label property as a fill in.

So perhaps we want to keep the logic where the tooltip won't show if its the same as the label and is being propagated by the label. But change it to always show if it was explicitly set regardless to whether or not it s the same as the label?

Additionally, we could also just replace the code that is looking for win-reduced on the parent and instead look our new closedDisplayMode classes but that whole process of making the command no about the AppBar or ToolBar states seems a little dirty to me.

**Comment by AmazingJaze** [comment]
Update inline Above, what I originally said makes no sense.

**Comment by rigdern** [comment]
The best option for MediaPlayer might be to:
  - Not use the `AppBarCommand`'s tooltip property (leave it blank)
  - Use the browser's native tooltip mechanism by setting a `title` on the `AppBarCommand`'s element.
