### ISSUE TITLE
WinJS 4.4: AppBar hides content all the time

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1500]
Upgrading from WinJS 2.1 to 4.4 is not painless even for the most simple apps that only have an appbar. In WinJS 2.1 the appbar does not cover parts of the main window in hidden state.
Just upgrading to WinJS 4.4 however does change this behaviour. The bottom part of my window is now always covered with the app bar and the text of the main window bottom not completely visible anymore.

This is the WinJS 2.1 Version

<img src=https://cloud.githubusercontent.com/assets/164625/10269950/197b6f70-6ae4-11e5-96d8-a2f5a77c5979.png height=50% width=50%>

And this WinJS 4.4

<img src=https://cloud.githubusercontent.com/assets/164625/10269951/197c2f00-6ae4-11e5-8788-be7b836ffef1.png height=50% width=50%>

Beside the much better type-ramp in WinJS 2.1 it shows the glitch of the appbar. Both views are scrolled to the maximum bottom. The text "See LICENSE info." is hiding under the appbar in WinJS 4.4

**Comment by AmazingJaze** [comment]
Hi @pke, I believe this discrepancy is a result of convergence work done in WinJS 3.X to run the same code for AppBar on phone and desktop. The AppBar in WinJS 2.1 for phone was rendered using a WP 8.1 system panel, similar to the virtual keyboard, and was not actually a part of the document. 

The AppBar is now rendered in the DOM using the same code on all platforms and in all browsers to create a more consistent experience for developers. Even with WinJS 2.1 you would have to code your App differently to use an AppBar in phone vs in desktop. The WinJS desktop AppBar has always been an HTML control since WinJS 1.0. and it was only for WinJS 2.1 when we first released WinJS for phone that the AppBar was rendered using system UI.

As such it is no longer possible to create the effect automatically where the AppBar will never cover your content, as it is designed to always overlay content while visible, whether or not its opened or closed.

The silverlining is that for any future UWP that you right, the AppBar will have the same API surface and mechanics across all screen sizes now. 

Overall I would guess that the changes to the AppBar design and  API in WinJS 4.X make it the possibly the most difficult control to migrate, particularly for WinJS 1.0 or 2.0 apps since many of the APIs like "sticky", "layout" have been replaced by "closedDisplayMode" and 'content' typed AppBarCommands. Please let us know if there are any additional AppBar scenarios in particular that you are no longer able to accomplish because of the change in design or API surface and I will do my best to help you through it.

For your current scenario, can you try adding bottom margin or padding to your content container? This will push any content that is in the flow of the document, but should not effect the AppBar since it is positioned out of flow.

**Comment by pke** [comment]
Thanks, @AmazingJaze for the explanation. Yeah I remember vagualy that WinJS 2.1 actually used the system to draw the appbar which also prevented it from hosting more than just command buttons.
Luckily my appbar scenario is very, very simple. I just want to give the content as much space as possible.

What about the type-ramp of WinJS 4.x Why is it so much bigger?

**Comment by AmazingJaze** [comment]
@jayrenn @jseanxu 
Can either of you comment on the new type ramp?

**Comment by jdalton** [comment]
Closing as stale, however feel free to comment with updates in your own time.
