### ISSUE TITLE
Reason for navigator.js pagecontrol position:absolute

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1533]
This always hits me when I want to make my app views printable. The inline style `position:absolute` in the pagecontrol prevents multipage print outs. What is the reason for this style anyway? Is it required for page transitions?

**Comment by toddpi314** [comment]
We rely on it for Title-Safe-Zones, since margin collapsing doesn't occur with Absolute (while still retaining relative layout in the parent container). 

In cases that either the Navigator or Page-Control ends up being the exclusive full-screen for a View, we need margins to be honored as is without any effect from the parent container outside of the navigation context. I know page-based apps aren't the only ones out there, but this is very helpful for that paradigm. 

+1 for keeping this the default in LESS

**Comment by Guadzilah** [comment]
Okay received message thanks

**Comment by pke** [comment]
I removed the style and everything (incl printing) works just fine in my Windows Store App. I don't care about cross-platform and what  WinJS is trying to achieve there. For me WinJS should really stay in the realm of Windows Store Apps and support __them__ 100% and not introduce things that actually make it __harder__ to develop for MS very own platform.

**Comment by toddpi314** [comment]
That's fair and a worthy set of priorities. 
We'll prep our apps for this to go override-side.

Thanks!

**Comment by Guadzilah** [comment]
Okay got it stay updated
