### ISSUE TITLE
intrinsics.css, intrinsics.js

### ISSUE THREAD

**Issue by StasD-Menulog** [winjs/winjs#1547]
Hi,
What are those "intrinsics" files, e.g. ui-light-intrinsics.css, intrinsics.js etc., why they are not included in winjs releases, and what is the 'official' way of getting them? Thanks.
And sorry for question in the "issues" section...

**Comment by mikewjackson** [comment]
These files are provided as a bridge as you migrate your existing WinJS code base to WinJS4.X. We do not recommend that you start a new project with them, and that's why they aren't included in the default release. 

For more information on styling please see https://github.com/winjs/winjs/wiki/Styling-HTML-Controls
