### ISSUE TITLE
SplitView + contentDialog = conflict

### ISSUE THREAD

**Issue by gilvandev** [winjs/winjs#1553]
When both elements are on a page, the buttons of the ContentDialog are not clickable. The ContentDialog closes only with ESC on the PC. In Windows Phone, you have to close the app

**Comment by AmazingJaze** [comment]
Hi @gilvandev 

Our recommendation is to put all overlay controls directly in the <body> to avoid this kind of problem.

In case you are curious to understand the reasoning behind our recommendation, here are some additional details. The recommendation is motivated by [stacking contexts](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context). When the Content Dialog opens, we put the full screen click eater element into the body which prevents you from interacting with anything other than the Content Dialog while the Content Dialog is open. We set z-indicies on the click eater and the Content Dialog so that the Content Dialog is on top of the click eater. For this to work, it's important that both of these elements are in the body's stacking context. The safest way to achieve that is to put the Content Dialog directly into the body. It's risky to parent the Content Dialog under a different element because if any of the Content Dialog's ancestors happens to be a stacking context (other than the body), then the Content Dialog will not interact properly with the click eater.

**Comment by AmazingJaze** [comment]
updated original response for clarity.

**Comment by gilvandev** [comment]
Perfect! But I have a question...

I'm setting up a system of insertion, modification and deletion of data. I'm going to be working with contentDialog to confirm several of these actions. I'm going to have to declare all the contentDialog in the body or can take advantage of a single element in all alerts?

**Comment by AmazingJaze** [comment]
@gilvandev  I believe you should be able to take advantage of a single element in all alerts, as long at the content dialogue element is declared in the body, it seems reasonable to just call methods that know how to configure the text and buttons inside of the content dialogue to however your app needs it at the time.

**Comment by gilvandev** [comment]
Nice...it's best work with confirmationDialog. Thank you!
