### ISSUE TITLE
Background Audio

### ISSUE THREAD

**Issue by gilvandev** [winjs/winjs#1606]
The background audio runs only Desktop Windows 10 app...in Windows 10 Mobile, it's necessary C# classes and much extra work to implement audio in background. Suggestions?

**Comment by niallatms** [comment]
Which particular WinRT APIs are you referencing?

**Comment by gilvandev** [comment]
Windows.Media.SystemMediaTransportControls with audio tag (HTML5)

**Comment by niallatms** [comment]
What do you mean by "it's necessary C# classes and much extra work to implement audio in background?"  Are the classes not available, or it's just hard to implement?

**Comment by gilvandev** [comment]
Hard to implement...In this example [https://code.msdn.microsoft.com/windowsapps/BackgroundAudio-63bbc319/](url) you can see 2 projects: a C# project and a C# + JS project to implement BackgroundAudio in WinJS App for Windows Phone 8.1. In Windows 10 Mobile it's necessary C# too
It would be interesting if WinJS implement background audio tasks in Windows 10 Mobile without C# to clean the implementation

**Comment by niallatms** [comment]
Here's the updated page for UWP: https://msdn.microsoft.com/en-us/library/windows/apps/Mt282140.aspx

It doesn't mention that you can't use JS for the background task; the APIs it references don't seem to be webhosthidden.

I don't think this is the right forum to address this since it seems more related to lower level app life cycle but I'll have to think of a better place to forward these questions/feedback.

**Comment by gilvandev** [comment]
Yes, I understand this is a matter of API, but it would be interesting to implement this in WinJS. Is something basic and can pick up many developers by surprise because in searching the internet, we see that on Windows Phone 8.1 deployment that is only using a C# class along with the Javascript.

I'd say it's something that should be implemented/researched in the future.

**Comment by mfycan** [comment]
Background audio always requires a separate project because it acts as an app by itself. The javascript implementation for it in UWP is broken or incomplete.

You will need to use the UWP C# sample for Windows 10 desktop/tablet.
For Windows 10 Mobile you will need to use the sample for Windows Phone 8.1 otherwise, when you publish the app, the background audio will always crash upon start.
When deploying you will need to target accordingly and use two separated packages: one for ARM and other for x86/x64.

I've been struggling with the same issue for months now and this is the only workaround I found.

**Comment by seksenov** [comment]
C# is not necessary for background audio on mobile. It also does not require separate project. You can register a JavaScript file to be the background task.

Check out this: https://github.com/seksenov/BGAudio sample project. BG Audio works on both mobile and desktop and it's written in JS.

**Comment by mfycan** [comment]
@seksenov Many thanks! I've been looking for documentation for long, even posted on msdn forums and nobody was able to help. There was not even a JS sample on the UWP sample projects.
The implementation on your code looks kind of hard to figure out for anyone trying to implement it but I'm glad it's possible.

**Comment by Gr8Gatsby** [comment]
@mfycan What build of Windows 10 Mobile?

**Comment by seksenov** [comment]
@mfycan glad it helps. I'll work on cleaning up the sample so it's easier to understand. It shouldn't be too hard to grasp once it's more readable.

**Comment by mfycan** [comment]
@Gr8Gatsby 10.0.10586.107

**Comment by gilvandev** [comment]
@seksenov great sample! Thanks! Microsoft sometimes let the documentation confusing in certain subjects and can further confuse developers. You already have a basic example?

**Comment by duyluandethuong** [comment]
@seksenov can confirm that your sample (as well as my owne music player project) cannot work correctly on Windows 10 Mobile (on PC, it works perfectly) Emulator. I attached the error which thrown out when you start to run the app. It says Out of Memory.

When I try to load the app to the real device (Lumia 950 XL), sometimes it works, sometime it does not. And neither the emulator nor the real device show music player controls when clicking the volume button.

This seem a bit weird since the Windows 10 Music app is written in WinJS as well. I'm not sure whether we need to implement a C# lib for this to work. I am pending my project due to this issue.

![capture](https://cloud.githubusercontent.com/assets/12383199/14138104/89fc4bce-f695-11e5-83b5-fa8b6f133f77.PNG)

**Comment by jdalton** [comment]
Closing as this looks out of scope for WinJS.
That's not to say the background audio discussion here can't continue.
