### ISSUE TITLE
Micon Instead of "Segoe MDL2 Assets"

### ISSUE THREAD

**Issue by xtoolkit** [winjs/winjs#1611]
hi
Please use Micon instead of Segoe MDL2 Assets to be fix html load in other os.
micon -> http://xtoolkit.github.io/Micon/

**Comment by cthedot** [comment]
Looks nice but what would be the advantage of using Micron instead of Segoe MDL2?

**Comment by xtoolkit** [comment]
Micon: MDL2 icon
winjs use "Segoe MDL2" az font system
but other os (ex.p: ubuntu) "Segoe MDL2" not exist in font system!

**Comment by gautamsi** [comment]
Why would someone like to use GPL in MIT licensed library, forcing everyone using this library to provide their commercial source???

**Comment by xtoolkit** [comment]
so, what can i do?
change licensed to? and port MDL2 icons to winjs?

**Comment by gautamsi** [comment]
if you can change license to MIT, it will be more open and integrate with other projects using MIT, GPL restricts and wants you to open the source. Even if Microsoft agrees to use your library, they will have to change the license of winjs to something compatible with GPL, MIT is not compatible with GPL. 

Given the previous experience, even if you change the license to MIT, MS may or may not include your library in WinjS due to legal issues, if this was so easy they could open source the Segoe UI font itself. 

Best thing would be to make it compatible with WinJS by inter-changable icon names, so that anyone can use it without breaking changes in their source.

**Comment by xtoolkit** [comment]
I changed license to MIT.

**Comment by xtoolkit** [comment]
hi
i release new update for micon repo
you can create custom font for winjs with this version
