### ISSUE TITLE
Project Status of WinJS

### ISSUE THREAD

**Issue by kanreisa** [winjs/winjs#1622]
Today, so many Issues/PRs hasn't touched.
It's bad experience :anger: 
What's going on? summer vacation? nap?
just please tell us the status.

**Comment by BenjaminGibbs** [comment]
Yeah an update on the status of the project would be good. Given nothing has really moved for a fair few months now.

**Comment by mesju** [comment]
Yes, what's going on with WinJS?

**Comment by jfranki** [comment]
I was just about to start trying WinJS to develop UWP apps with angular for my company, but until any official announcement is made making sure this is not in any way abandoned I am not wasting my time...

**Comment by rrivani** [comment]
Any news?

**Comment by xdvarpunen** [comment]
People of WinJS(@jseanxu,@rigdern,@xirzec) don't seem working anymore. Though this happened: http://www.zdnet.com/article/microsoft-is-adding-universal-windows-platform-support-to-facebooks-react-native-framework/ React-Native allows to create UWP applications in Javascript where Microsoft and Facebook are collaborating together.

**Comment by humale** [comment]
Hey everyone. Like @llongley mentioned, we're ramping up on this space, and will be the points of contact for issues/pull requests moving forward.

**Comment by BenjaminGibbs** [comment]
That is awesome @humale; do you or @llongley have any roadmap going forward you could share? or are you just picking up bug fix's etc.. on the whole? 

I am building a UX using WinJS/Angular but don't want to heavily invest the tech if it is in maintenance mode so some clarification would be welcome if at all possible.

**Comment by diegosa06** [comment]
This still begs the question, is WinJS still been actively developed on i.e. new features. How many people working on it? Has the team been downsized?. It looks to me as a close to another abandoned project again from Microsoft. Please make up your minds on what you want to do, instead of messing with people like this and not saying anything official.

**Comment by jfranki** [comment]
@diegosa06 I think you are spot on, unfortunately. It really seems that WinJS has entered in _maintenance mode_ and they only assigned minimum resources to it to finally abandon it completely at some time in the future... At least that is the impression that I have when they tell me that **2 guys** will be the point of contact for issues/pull requests. I am glad they are developing Project Islandwood and porting win32 programs, but discarding web developers is not a good idea when they could be introduced easily to UWP.

**Comment by xdvarpunen** [comment]
@jfranki UWP is tied to Store, Store is tied to Microsoft account, Microsoft account is tied to internet connection. UWP apps cannot be used privately or as standalone application. Basically UWP ties your hands when trying to share or use privately.

UWP gave impression that it works best with C#/XAML.  [React announcement](https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/) gave impression that C#/XAML is still best:

> In the case of React Native on UWP, the view managers and native modules are implemented in C#, and the view managers instantiate and operate on XAML elements. 

And JavaScript role here is just

>...the framework translates the React DOM from JavaScript into method calls to view managers on the native platform, allowing developers to proxy direct calls to native modules through JavaScript function invocations

JavaScript role in Windows application has been dropped to be wrapper/caller while C# is back again as dominating/priority one programming language. It's big change considering their roles in Windows 8 and Windows 10. And .NET it's not really polyglot. C# has been priority number one for long time now. Maintenance mode for WinJS looks thus most logical.

This is my view right now :/ please broad my view if am wrong/lost.

-XDVarpunen

**Comment by diegosa06** [comment]
There are people using WinJS purely for HTML 5 web development, not just UWP apps.....

**Comment by humale** [comment]
@BenjaminGibbs , @diegosa06 , I want to help you make smart decisions about using WinJS; thanks for asking.  Right now, we're planning to maintain WinJS's existing features--this means responding to Issues and Pull Requests on a regular basis.  We're committed to making sure that WinJS continues to run well.  

We don't have plans to invest in new features or feature requests.  @diegosa06 pointed out that WinJS is used in a variety of ways and we want to make sure that we continue to support it; we also want to set expectations that we're not planning to release a new version at this time.

If there are any questions about this, please feel free to ping me or @llongley--I definitely want to keep you as informed and supported as I can.  There have been a few questions about this on different Issues, so I'll update the Readme to make this clearer.

**Comment by englishextra** [comment]
> The king is dead, long live the king!

Is the new king C#/XAML?

**Comment by cthedot** [comment]
Javascript is one of the biggest languages on earth currently. So why abandon all efforts here? As a webdeveloper developing native apps with JS has just been great and WinJS helps a lot. I admittedly only use a few BUT important features like appbar, ListView or Hub but still a great project. 

Where or to whom can we as webdevs or JS devs complain (or beg ;) Microsoft keeps investing here?

**Comment by humale** [comment]
@cthedot I'd recommend opening up a feature request on UserVoice, one of our feedback tools.

**Comment by pke** [comment]
It seems the situation is pretty clear. MSFT initially wanted to win over Webdevelopers for the new Windows 8 platform. But they did not came and built apps with JS/HTML. MSFT calculated that since more people know HTML/JS than objective-C and Java they would eventually create (inofficial) big apps missing in the store. It did not happen. Developers did not convert their iOS/Android apps to Windows, despite the very low entry proposition of HTML/JS. Why? I don't know.
I do know, every time I see the XAML people struggling with basic resource and style management that has been solved way better in HTML/CSS for years now, I cringe and go back to HTML/CSS. And they have to write awfully verbose XAML.

Internally XAML became the new Windows 8.x first class platform for the OS. I like to believe in the beginning the race between HTML/JS and XAML/C# was open. Any why wouldn't it? HTML/CSS/JS is in no way less powerfull than XAML/C#. It runs very fast in MS Internet Explorer. MS could have decided to code the startmenu in HTML/JS too, but I guess they have been burnt once with an `Active Desktop` based on IE back in old '98 and wouldn't risk it again.

So you all can pretty much forget about this platform at this time. Luckily one does not need `WinJS` to develop Windows apps in HTML/JS. And since Windows 10 looks like Android anyway, why not pick one of the many `Material UI` libs out there and develop a Android/Windows Hybrid app with `Cordova`. Sidenote: With MSFT's urge to please the Android users the MS Design Language (we call it `Metro`) was moved towards Android (`Material Design`) and all the signature Windows design elements from Windows 8 are gone. Gone is the rich canvas, hello Hamburger menu. Gone are unique features like unified app, print and sharing UX (not related to WinJS).

I am currently developing an iOS/Android/Windows app using `react` and `cordova`. Works and looks great. One wouldn't know its an HTML app for 99% of the time.

**Comment by cthedot** [comment]
Maybe not many Webdevs did jump onto Win8 but there are a few including myself ;)

And yes, WinJS is not a requirement but I do like and use some items of it list ListView or the Appbar implementation. If you use React, Angular or whatever does not matter I agree and that actually is a good thing (I use KnockoutJS as I know it best, guess depends very much which year you started webapp development and which was the library of the year at the time ;)
I don't think many people use or will use WinJS for apps outside UWP though so maybe the focus of WinJS should change to optimize it for that and not as a general UI framework. Maybe I am wrong about that though?

But I don't think (and also heard) that MS is NOT phasing out Javascript for UWP.

Re Metro successor is now Material UI: 
Material UI heavily borrowed from Metro. Windows 10 borrowed some stuff back (mainly hamburger which IMHO was wrong but whatever) but it still has its own elements and style and will hopefully develop in its own direction further.
The unified and Settings, Print and share stuff was probably too advanced and people just did not use them in addition to the press ridiculing Win8 as a complete UI failure. (BTW initially Search was unified too which was to be expected to not work as it did not work on WP7 either and they stepped back from that in WP7 and then Win8 later. Sometimes MS does strange things, only think of the Skype mess). 

But maybe the unified positioning of triggering settings, print or share was not that great anyway. As long as the contracts (esp. share comes to mind) are still there which each app can use and just put a button to open it anywhere inside its own UI this still works great. And as apps like Edge do incorporate this themselves the functionality is more visible for end users too. So it may be a little bit more work (add a print, share button in your app) it is way better than the older iOS model of each app having to support each and any service themself. Some WIn apps still do that or have both own share options and system share (I think NextGenReader does this).

**Comment by pke** [comment]
@cthedot True points you mention. Hidden UX like the charms bar can be a problem, but its a joy to work with on a tablet device. Two simple gesture you head to learn. Too much for the united press of Stupidistan, that wanted their beloved start button back. The same press the cried when the Program Manager was replaced by the Start button. A START button that you have to use to SHUTDOWN your PC. Ouch. The same press then wanted that off button on the Windows 8 start menu, because in 20 years they had no learned that they can simply switch off the PC with the physical buttons. That worked since Windows 9x with ATX boards, and soft power switches.

Microsoft did an exceptional bad job ob promoting the start menu just as a bigger start button. Where everything the start button could do also worked. How many people that claim, only by the endless sub menu mazes they created by hand in their startmenu, they can work _professionally_, how many of those know that you could always much faster find a program in the start menu/start screen by typing the first 3 letters of said programs?

The hambuger menu is worse than the Charms bar, because the number of functions and app features hidden in it differ from app to app. At least with the charms bar you learned it once and could use it in every app the same.

MS should have opened up the WinRT API for desktop app much sooner and let them participate in the Windows 8 ecosystem. They missed a big opportunity there to win over Win32 developers.

Windows 10 is a desaster for Tablet UX in so many ways Windows 8 was not (no virtual desktops in tablet mode WTF), but that is totally Off-topic here.

**Comment by BrandonLive** [comment]
What would you want to see in WinJS that isn't better off in the HTML/JS/CSS platform itself, or in another framework/library like Angular, Ionic, ReactJS, etc?

I think the main point is that WinJS does what it does, and will be maintained. It's open source and you can submit PRs with anything you want to add or update. It just doesn't make sense for MS to focus energy on new features here since they'll get better adoption if they're added as contributions to those more popular and heavily funded frameworks, or added to the platform itself.

I think it's very important not to conflate the WinJS library (a set of utilities and controls you _can_ use for apps or web sites if you choose to) with JS UWPs. Some of the top apps, like Netflix, Pandora, and Shazam (not to mention my own app, Tweetium) are JS UWPs. But a lot of apps have little or no need for WinJS these days as they already have code using Angular, Ionic, ReactJS, and so on.

**Comment by mseddon** [comment]
@pke Cordova for wp and windows is, in fact built on WinJS.

**Comment by pke** [comment]
@mseddon only the life-cycle stuff. And that could also be implemented using plain WinRT calls. I don't really like the dependency on the WinJS lib in Cordova.

**Comment by pke** [comment]
@BrandonLive WinJS should have never diverted to please the Web crowd. It should have stayed loyal to Windows Apps and support them in the best way. It doesn't. But as you said, its probably not needed anymore and in my recent apps I stayed away from it and did not miss much.

**Comment by mseddon** [comment]
@pke ah, right.  I agree it would be good to separate that out if possible.

**Comment by diegosa06** [comment]
Good day, will there be any update on WinJS with bug fixes. Not seen any maintenance releases yet?

**Comment by pke** [comment]
@diegosa06 As I wrote here several times, the project seems to be dead. MS is concentrating on Xamarin now and seems to have abandoned.
It was a great way to develop (sophisticated apps). You could always add CPU intensive stuff via C++ components and could really build mature apps with this framework, despite its several glitches (most of them came in after 2.x when they decided to become "webfriendly"). I have built 2 big industrial apps based on WinJS and they work very well.

But I consider this project dead and moved on.

**Comment by diegosa06** [comment]
I use WinJS for my Dashboard HTML 5 web page. I use primarily the split view, toolbars. menu and the contentdialog. Are there libraries out there with similar functionality and look&feel?

What libraries Microsoft is using for their own HTML 5 website development?

**Comment by pke** [comment]
I just coded all the components I needed for my apps myself now. I target specific devices so I don't care about IE<11. In that regard I cannot recommend any other framework, I am sorry.

For the DevCenter dashboard MS seems to be using Angular. And it behaves like you would expect. Slow and sluggish.
I am pretty sure they also still use ASP in most of their pages. Heck, even the different versions of the MSDN use different styles and behaviour.

**Comment by hiepxanh** [comment]
xamarin is poor and weak, just 2000 star repo, event weaker than Native-Script, cannot compare to Ionic, and is nothing with React Native or React. Why they abbandon this. I wan't to come with Microsoft and he push me away
