### ISSUE TITLE
No way to disable XYFocus

### ISSUE THREAD

**Issue by lakichemole** [winjs/winjs#1629]
Hi,

We are using WinJS but apparently there is no way to disable the XYFocus, from its registration (on ready event) it add 2 listener on keydown which cannot be disabled. We have our own Focus manager and don't want to use the one from WinJS.
Only solution will be to change the base.js winJS code. Its kind of global reflexion abou the possibility to disable or configure control/module in WinJS the fact that a lot of constant which can be useful externaly are not accessible, like the one's used for css class ('win-disposable") ...

Romain

**Comment by humale** [comment]
Hi @lakichemole. I think this would be more along the lines of a feature request, and so we probably won't be doing this. Refer to the readme for the status of WinJS.

**Comment by AmazingJaze** [comment]
@lakichemole @humale 

It used to be the case that any element could be annotated with the "win-xyfocus-suspended" class and xyfocus navigation algorithm would ignore any focus request when the source of the input comes from within that element or its children. 

For example, the WinJS ListView control suspends XY focus since it has its own algorithm for focus management. I imagine if you wanted to turn of xy focus completely you could try adding the "win-xyfocus-suspended" class to the <body> element of your page.

**Comment by AmazingJaze** [comment]
This unit test appears to validate the feature: https://github.com/winjs/winjs/blob/00bb51bde18d4ea81fa2871b87d1a4ed550267d9/tests/UI/XYFocus.ts#L597-L622

**Comment by lakichemole** [comment]
Thank you, that's good to know, but anyways we had to extract it from winjs, do some hack to prevent it to listen anything, and then modify the code to improve performance (example of improvement, instead of querying all element every time, add a specific css query like '.win-focusable,button, div[tabIndex]' and customize it. So it was more about preventing xyfocus to start to be able to use our own way
