### ISSUE TITLE
Is there a way to prevent the user from re-ordering certain elements in ListView?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#691]
My listview should be sortable by dragging. However, the first n-entries should be static. That means they themself cannot be dragged to another position within the listview and no item can be dragged between them.
Is this possible with the `ondragstart/ondragend` events?

**Comment by TheWrathOfConst** [comment]
You're right about win-nonselectable being removed by the ListView. It turns out we do actually remove the class when we're not in a phone-only WinJS build. I need to change my recommendation: Instead of using win-nonselectable, listen to the [selectionchanging event](http://msdn.microsoft.com/en-us/library/windows/apps/br211850.aspx) and remove the items that should not be selectable/draggable from the selection manually.

You're using the render method correctly. renderComplete is used when you want to have a multi-stage item rendering pipeline. Generally you would do the fast stuff inside your renderer (creating simple DOM nodes, placeholders, etc) and then do extra processing inside of renderComplete to handle the really slow/async stuff. When you have a fast item template that doesn't do slow work, it's usually unnecessary to use renderComplete.

I'll open a bug on our documentation team and get renderItem documented properly. Thanks for bringing that up!
