### ISSUE TITLE
Toggle switch design moving away from Windows design

### ISSUE THREAD

**Issue by kollster** [winjs/winjs#744]
With recent updates of WinJS the visual design of the ToggleSwitch has moved away from the normal Windows ToggleSwitch appearance. The new WinJS ToggleSwitch has a strange design with rounded corners that seems out of place in most Windows applications. I do not understand this visual design change. Why has it happened?

![toggleswitch](https://cloud.githubusercontent.com/assets/3436707/5157538/f02d8a32-7312-11e4-8ecc-3583e7cda697.png)
To the left we see the new WinJS ToggleSwitch and to the right we see the normal Windows ToggleSwitch.

Please let us use the normal Windows design for the ToggleSwitch again!

**Comment by pke** [comment]
Seeing this awful non-Modern UI toggle to creep into the Windows Phone 10 preview I really start to worry. This seems to be a serious design language change (alongside the awful Hamburger menu) and totally inconsistent with the rest of the rectangular UI elements. Too much Android influence on Windows lately for my taste, and not only for my as uservoice votes on this issue proves.

**Comment by xirzec** [comment]
@pke - Thanks for participating in UserVoice. I've also forwarded your comments on to the design team.

**Comment by pke** [comment]
Thanks Jeff. You know, we developers appreciate the new openness MSFT shows the recent years. It really feels like they are listening and caring for the developers. I also understand that MSFT is behind iOS and Android in terms of market share but they are (were) miles ahead in visual style and UX. The Metro design language is still unique although iOS and Android going similar ways now. Every first time user I gave my phone was instantly hooked and surprised about the easy of usage, smoothness of the animations and overall handling of daily tasks.

MSFT is also listening to the consumer voice more now, the new-old startmenu only the press seemed to be bitching about, is back. No "real" Win8 user ever missed it. But that's ok, if dinosaur XP users can then easier go to Win8. I remember the discussions in Usenet back in '95 when Windows introduced the Start Menu the first time and people complained about the missing "Program Manager". Yikes.

I, for one, am missing the original unique Win 8 search contract. It was such a fresh way to unify search across apps. It needed just a little improvement. Instead MSFT crippled it to what it is now, maybe also due to user complaints of the feature being to advanced for some/most users.

I also understand that maybe by modifying the new Windows Design Language MSFT tries to get more users over from Android and iOS. But you scare Windows users away at the same time. If we want Android looking UI we will buy Android hardware.

What I am saying is: MSFT seems to listen to the voices raised from the outside, as some examples  I mentioned here seem to prove. Maybe they will revert this decision of Android'ing the UX and favouring the Hamburger button over the Pivot/Hub control.

PS: The old Win 7.5/8 Phone Photo hub was beautiful with its random background photo and large font language using the Pivot design. The new one in 8.1/10 is a huge step back.

**Comment by dougestey** [comment]
@pke I, too, am extremely sad to see the new design direction of Windows 10 interface controls. It's disappointing to see the core concepts that set Windows design apart from the other players cast aside. The old pivot controls, in particular, will be sorely missed.

**Comment by pke** [comment]
It seems MSFT is really serious about the design distortion. 
![windows phone 10 ugly toggles](https://cloud.githubusercontent.com/assets/164625/6666771/e567cc2e-cbe7-11e4-90c3-d2a3aa54acf4.jpg)

Care to explain why this move away from rectangular controls was made and why its so inconsistent?

**Comment by acnodelabs** [comment]
Cross-Platform is basically about convergence and that is reflecting in design too.
