### ISSUE TITLE
WinJS.Rating + PointerEvents bug

### ISSUE THREAD

**Issue by claudiosvcc** [winjs/winjs#791]
Using WinJS + Polymer (PointerEvents) we found this exception in Chrome & Firefox browsers (didn’t tested in IOS) when using Ratings:
“InvalidPointerID”, which avoids Rating control to fire pointerdown.
There’s a repro in http://1drv.ms/1COemcI

It seems that the value set for POINTERID (-1) in mouseEventTranslator (which is in base.js), is not changed to a known value of PointerEvents. Therefore, the exception is thrown when Rating tries to lock “Capture” in PointerEvents.

**Comment by phosphoer** [comment]
# Issue 
The problem here is that WinJS checks for the existence of `PointerEvent` once at startup, and never again. Since you are including WinJS before the pointer event shim, it incorrectly tries to use its own internal shim. 

# Workaround
Include WinJS after your pointer event shim, and it will work properly. 

# Long term
We should look into doing this check in a more flexible way, perhaps each time we are about to use our   own shim we should check that another hasn't been added.
