### ISSUE TITLE
Height of primary row in AppBar with Menu layout should not take up full height (48px) when there are no primary commands for minimal AppBar

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#793]
For both closedDisplayModes "minimal" and "compact" the primary row is 48px when there are no primary commands. I believe the design calls for 24px when there are no primary commands.

**Comment by mkjunior19** [comment]
This bug only applies to 'minimal' AppBar. It is by design for 'compact' AppBar to have the primary row of 48px when there are no primary commands. 

This is the desired experience: 
Minimal closed AppBar with no primary commands
![minimal_noprimary_closed](https://cloud.githubusercontent.com/assets/6732783/5633678/8f3d489a-958e-11e4-90e3-56cdbaa0eba2.png)
Minimal opened AppBar with no primary commands
![minimal_noprimary_opened](https://cloud.githubusercontent.com/assets/6732783/5633680/949c51be-958e-11e4-88bd-585f0235d44a.png)

Compact closed AppBar with no primary commands
![compact_noprimary_closed](https://cloud.githubusercontent.com/assets/6732783/5633682/9728a7de-958e-11e4-867c-da08cb36160c.png)
Compact opened AppBar with no primary commands 
![compact_noprimary_opened](https://cloud.githubusercontent.com/assets/6732783/5633686/9aa97776-958e-11e4-8d00-4604762e2719.png)

**Comment by AmazingJaze** [comment]
We believe we can live with the discrepancy described above. If this becomes problematic in the future, we can reconsider.
