### ISSUE TITLE
Menu can hang Firefox

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#830]
1. Download the repro page from http://1drv.ms/139xdhE
2. In Firefox, open repro\index.html
3. Click "Show Menu"
4. Invoke the last command labeled "menu"
5. Invoke the last command labeled "menu"
6. Try to move focus within this third menu

Unexpected result: Firefox is frozen. You cannot interact with the menus anymore.

**Comment by AmazingJaze** [comment]
This appears to be a FireFox infinite loop. A reduced repro is loading an HTML page with the following markup and pressing the TAB key.
```HTML
<!doctype html>
<html>
<head>
    <title>HTML Template</title>
</head>
<body>
    <div id="testdiv" role="menu">
        <button role="menuitem" aria-owns="testdiv">
            crash
        </button>
    </div>
</body>
</html>
```
I've opened a bug on Firefox:https://bugzilla.mozilla.org/show_bug.cgi?id=1122846

When you have two nested html elements with the roles ```menu``` and ```menuitem```, setting the "menuitem's" ```aria-owns``` attribute to be its parent element and then interacting with that element is enough to cause an infinite loop in FireFox.

This problem manifests itself through WinJS today when you set the MenuCommand's ```flyout``` property to be a Flyout or Menu with MenuCommands that are already higher up in the aria ownership tree.  MenuCommands set the `aria-owns` property on their element to be the id of the Flyout element in the MenuCommand ```flyout``` property setter.

A simple WinJS Repro would be:
```JS
window.menu 1 = new WinJS.UI.Menu();
window.cmd1 = new WinJS.UI.MenuCommand((), {type: 'flyout', flyout: menu1})
menu1.commands = [cmd1];
```
Interacting with cmd1 will cause the hang.

And a slightly more complicated repro is:
```JS
window.menu 1 = new WinJS.UI.Menu();
window.menu 2 = new WinJS.UI.Menu();

window.cmd1 = new WinJS.UI.MenuCommand((), {type: 'flyout', flyout: menu2})
window.cmd2 = new WinJS.UI.MenuCommand((), {type: 'flyout', flyout: menu1})

menu1.commands = [cmd1];
menu2.commands = [cmd2];
```
Interacting with cmd2 will cause the hang, since it creates a circular ownership hierarchy.

Sending back to triage for further discussion. I don't think we expect or recommend developers to set a MenuCommand's `flyout` property to be a Flyout or Menu that is higher up in the cascade, but only FireFox seems to get caught up in an infinite loop.

**Comment by xirzec** [comment]
Seems like this is just something we shouldn't support - there isn't a user scenario for circular menus, is there?

**Comment by AmazingJaze** [comment]
I don't think there is a scenario where we would ever want to support circular menus. One potential scenario where a developer might hit this is if they had defined a cascade of a few menus already, and then while that cascade was hidden, wanted to dynamically reorder the cascade, by inserting the last node somewhere further up the cascade. If they don't remember to null out the `flyout` property linking the previously second to last flyout in the cascade, to the flyout that was just reinserted higher up, then they could run into this the next time the entire cascade is shown.

This is really no different than the problem you would face with reinsertion of Nodes in a typical linked list, but its also probably is not clear to end developers that they need to be responsible for cleaning up.

I will resolve as external for now
