### ISSUE TITLE
Searchbox: Sample should show how to do hint text

### ISSUE THREAD

**Issue by pag3** [winjs/winjs#848]
Feature: Searchbox
Environment: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; rv:11.0) like Gecko
Source: http://try.buildwinjs.com

It would be great if there were a sample for the search box that showed how to have 'hint text'.

**Comment by jayrenn** [comment]
The Searchbox control has been deprecated. Use the [AutoSuggestBox](http://try.buildwinjs.com/#searchbox) control instead.

In order to set the hint text, use the `placeholderText` [property](https://msdn.microsoft.com/en-us/library/windows/apps/dn919954.aspx). Here's a snippet from the [Try Site sample](http://try.buildwinjs.com/#searchbox:simplelist1):

```html
<div data-win-control="WinJS.UI.AutoSuggestBox" data-win-options="{
    placeholderText: 'Type a city',
    onsuggestionsrequested: Sample.suggestionsRequestedHandler,
    onquerysubmitted: Sample.querySubmittedHandler
}"></div>
```
