### ISSUE TITLE
Modules: Promises missing a dependency

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#852]
1. In `WinJS.js`, comment out all dependencies except the line for `WinJS/Promise`
2. Use `grunt` to create a build
3. Try to use the `WinJS.js` file that gets output

**Unexpected result:** An exception is thrown in `WinJS.js`. Typing `WinJS` in the console shows that the namespace doesn't exist. In order to fix this, I needed to include `WinJS/Core/_WinJS` and `WinJS/Core` as dependencies in `WinJS.js` in the `src` folder.

**Comment by xirzec** [comment]
I was able to produce a Promise-only build without including `WinJS/Core`. 

The `Core/_WinJS` dependency is required so that the AMD shim can re-export the WinJS object to the global namespace.

```js
define('WinJS/Core/_WinJS',{});
```

```js
require(['WinJS/Core/_WinJS', 'WinJS'], function (_WinJS) {
    global.WinJS = _WinJS;
});
```

Unfortunately r.js isn't smart enough to parse this requirement out of the footer, so it has to be manually included.
