### ISSUE TITLE
VS warns about inconsistent line endings in built WinJS

### ISSUE THREAD

**Issue by xirzec** [winjs/winjs#878]
The r.js optimizer seems to be inserting only \n instead of \r\n when concatenating together our modules:

![image](https://cloud.githubusercontent.com/assets/639216/5728313/3185608a-9b1e-11e4-8da6-6a84f9e85e8c.png)

This causes warnings in VS when the file is opened. We should figure out a way to normalize these.

**Comment by phosphoer** [comment]
Since r.js doesn't seem to be configurable regarding what line ending to use, we'll probably have to solve this by adding a build step that normalizes endings. 

One such plugin to do this is [grunt-lineending](https://github.com/suisho/grunt-lineending), or we could also just write a simple plugin similar to our add-bom one.

**Comment by xirzec** [comment]
Which do you recommend?

**Comment by phosphoer** [comment]
I'm right now experimenting with creating our own line endings task.
