### ISSUE TITLE
Add underline to hyperlinks 

### ISSUE THREAD

**Issue by nizh914** [winjs/winjs#893]
In order to make our hyperlinks more accessible, we should add an underline to them. This ensures users know that the hyperlink is actionable base on more than the color.

**Comment by pke** [comment]
I think Windows Store app developers (am I the only one? ;)) would appreciate a less breaking approach to all those style changes introduced with WinJS 4. How about leaving the old styles for Windows Store apps in the stylesheets with additional selectors so we app devs can just add a class to our default.html body element and get the old Store styles back?

```
a.storeApp {
  color: #4f1acb;
}
a.storeApp:hover:active {
  color: rgba(79, 26, 203, 0.6);
}
a.storeApp:hover {
  color: rgba(79, 26, 203, 0.8);
}
``` 

```
<body class="storeApp">
```

or provide a Windows Store apps CSS without all those "Web" changes.

Now every developer that relied on the default WinJS styles has to override all those new changes with custom style rules.

**Comment by pke** [comment]
I have a hard time selling WinJS 4.0 to my clients because of all this non-Windows-App-Store adjustments that hurt existing Windows Store apps written with WinJS.
I mean come on, is anybody even using WinJS on websites yet?! So why all these changes that do more harm to Windows Store apps than tracking attention to WinJS in the web world?

**Comment by toddpi314** [comment]
+1 for upgrading the styles and not supporting backwards compatibility beyond major version.

Reasons:
- Older versions of WinJS are open source 
- Older versions of WinJS are snapshot (and won't go away)
- Newer versions are designed for the new Windows 10 design strategy 

MS already committed to broad changes to WinCore and the non-js UI controls. 
Let's stick to the plan and make WinJS awesome for the next 5 years, not the last.

**Comment by pke** [comment]
Which WinJS app in the current store uses underlined links?

**Comment by toddpi314** [comment]
My argument is weak if you look backwards. Strong if looking forwards.

If you are looking for evidence of necessity in the WinJS 2.0-3.0 baseline apps, which I gamble is a large % of the current store, you won't find it. That is because those classes of apps are pretty isolated to the store and have no reuse else-where.

WinJS 4.0 presents an opportunity for future developers to not be in the boat you are in now. The only way that happens is if the baseline design is compatible cross platform. Then, with the web-apps model it will really make since to write once (most likely for the web since that is a larger avenue of traffic than the store) and accelerate in the WinCore context.

No complains here on your feedback. Just wanted to share that I personally feel making the WinJS design more web compatible is a good thing for us all!

**Comment by pke** [comment]
I hear you. I still think a less forced way of putting new styles in place would have been better to existing WinJS apps. What's wrong about to let WinJS apps retain their styles by adding a class to their body element as I mentioned so they profit from bugfixes and features of WinJS 4.0? Or backport 3.x fixed done in WinJS 4.x Otherwise its not fair and also uncommon for MS, who still retains Win 1.0 APIs to this day, to break "old" apps.
