### ISSUE TITLE
Error in XYFocus when running on a worker

### ISSUE THREAD

**Issue by gleborgne** [winjs/winjs#924]
With latest source, following code is triggering an error (Key is undefined) when referencing WinJS in a worker :

exports.keyCodeMap = {
        left: [_ElementUtilities.Key.leftArrow],
        right: [_ElementUtilities.Key.rightArrow],
        up: [_ElementUtilities.Key.upArrow],
        down: [_ElementUtilities.Key.downArrow]
    };

**Comment by xirzec** [comment]
This is because _ElementUtilities bails out when in a webworker:

````js
// not supported in WebWorker
if (!_Global.document) {
    return;
}
````

If you want to use WinJS in a worker, you might want to consider doing a custom build. The easiest way (if you're already building our source) is to go into `src\js\WinJS.js` and comment out everything you don't need, including XYFocus. One note is that you have to leave the very first require of `WinJS/Core/_WinJS`. Then rebuild.
