### ISSUE TITLE
swipeBehavior select doesn't work.

### ISSUE THREAD

**Issue by andrii-morozov** [winjs/winjs#935]
I have tried to specify swipe behavior select.  For 3.0.1 it is not working in Chrome. In [Try WinJS](http://try.buildwinjs.com/#listview:selection) it doesn't work at all (I have changed the settings to swipeBehavior select).

**Comment by TheWrathOfConst** [comment]
Swipe to select only works inside of IE. This is because the swipe gesture is implemented by the platform, and IE is the only platform that supports `touch-action: cross-slide-x`. 

We're moving away from using the swipe gesture in WinJS. WinJS 4.0 no longer uses swipe, and has deprecated the `swipeBehavior` properties in `WinJS.UI.ItemContainer` and `WinJS.UI.ListView`.

**Comment by andrii-morozov** [comment]
Thanks, but this is quite unfortunate, we have a lot of functionality build using swipe. We would have to change design cause of this. Basically the idea is that on click we are showing edit screen and on right click/swipe we are selecting after removing swipe we would have to add checkboxes,

**Comment by TheWrathOfConst** [comment]
Checkboxes for selection are implemented  in the 4.0 ListView. To get them to appear, put the ListView into this mode by setting `selectionMode` to `multi`, and `tapBehavior` to `toggleSelect`. You can turn off this mode by changing `tapBehavior` back to `directSelect` (or `invokeOnly`, if you prefer). We recommend using an AppBar or ToolBar and adding a command to it to toggle between selection mode and normal mode.
