### ISSUE TITLE
ListView: <title here>

### ISSUE THREAD

**Issue by PrachiThakkar** [winjs/winjs#948]
Feature: ListView
Environment: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Source: http://try.buildwinjs.com Play With ListView
Layout: Grid
Orientation: Vertical
Items Reorderable: False
Items Draggable: True
Tap Behavior: Invoke Only
Swipe Behavior: Select
Selection Mode: Multi
Item Template: Inline
Group Items: True
Group Header Template: Text With Image
Group Header Position: Top
Group Header Tap Behavior: None
Data Source: 10000 Items

**Comment by rigdern** [comment]
Closing because it looks like this issue may have been filed accidentally from the "Play with ListView" page on the Try Site.

@PrachiThakkar, if you meant to file this bug, please open a new one with a set of repro steps for triggering the bug and a description of the expected and actual behaviors.
