### ISSUE TITLE
Cross-Origin XHR on error always returns status 0

### ISSUE THREAD

**Issue by lamuertepeluda** [winjs/winjs#949]
**steps to reproduce**
Say I have the WinJS app running at http://www.mysite.com/

If I do a CORS request:
```javascript
 WinJS.xhr({url:"http://www.othersite.it/pageOrApiThatDoesNotExist"}).then(
function onSuccess(xhr){console.log("OK",xhr.status, xhr.statusText);},
function onError(xhr){console.warn("Error",xhr.status, xhr.statusText);}
);
```
I *always* get xhr.status=== 0 and statusText==="" in the error handler, especially when ACAO headers is not set on the server.

For local or same domain request all works fine.  

With regular XMLHttpRequest I get all the statuses.  
I also do not understand why my global **WinJS.Promise.onerror** handler gets fired (several times) before my local error handler (**onError**) gets called: I expected to be able to intercept errors *before* the global handlers...

**Comment by rigdern** [comment]
> I always get xhr.status=== 0 and statusText==="" in the error handler, especially when ACAO headers is not set on the server.

> With regular XMLHttpRequest I get all the statuses.

What browser are you testing this in? I am getting status=0, statusText="" with `XMLHttpRequest`. Here's my test page (I ran it under a local web server and try.buildwinjs.com does not have ACAO headers):

```html
<!doctype html>
<html>
    <head>
        <title>XHR</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <style>
        </style>
        <script>
            function fetch() {
                var req = new XMLHttpRequest();
                req.onreadystatechange = function () {
                    if (req.readyState === 4) {
                        console.log("Status: " + req.status);
                        console.log("Status Text: " + req.statusText);
                    }
                };
                req.open("get", "http://try.buildwinjs.com/notFound.html", true);
                req.send();
            }
        </script>
    </head>
    <body>
        <button onclick="fetch();">Fetch</button>
    </body>
</html>
```

> I also do not understand why my global WinJS.Promise.onerror handler gets fired (several times) before my local error handler (onError) gets called: I expected to be able to intercept errors before the global handlers...

This is the expected behavior of [`WinJS.Promise.onerror`](https://msdn.microsoft.com/en-us/library/windows/apps/br211868.aspx). It fires for every error promise regardless of whether or not the error is handled. In your `WinJS.xhr` snippet, `WinJS.Promise.onerror` fires two times: once when the promise returned by `xhr` enters the error state and once when the promise you created with the `then` enters the error state.

If you are only interested in unhandled promise errors, you can make use of [`WinJS.Application.onerror`](https://msdn.microsoft.com/en-us/library/windows/apps/hh974768.aspx). Note that to make use of `WinJS.Application` events, you have to call `WinJS.Application.start()`.

**Comment by hirandesai** [comment]
I'm facing similar issue... but in my case the CORS headers does exists still it executes error block.
To check whether CORS are really working, I enabled CORS on my Web API and created a new web project. Used jQuery.Ajax for sending request to Web API and it worked (I also disabled CORS just to varify if it gives error and it indeed threw error).


![1](https://cloud.githubusercontent.com/assets/18441068/16222405/76c2a34e-37b5-11e6-8c00-376e8ba7a9d0.png)
![winjs_error](https://cloud.githubusercontent.com/assets/18441068/16222407/77629c3c-37b5-11e6-859d-6457be28ce8a.png)

The first image shows that I have CORS error on my API. The second shows that it's executing the error block with staus code of 0.
