### ISSUE TITLE
WinJS animation not working as intended?

### ISSUE THREAD

**Issue by ravindrakumarks** [winjs/winjs#960]
WinJS.UI.Animation.enterPage doesn't work when overriding default values.
something like ```WinJS.UI.Animation.enterPage(element, { top: "100px", left: "0px" })``` doesn't fade or translate, until it is paired with ```WinJS.UI.Animation.exitPage()```

Also, trying to use custom animation using ```WinJS.UI.executeAnimation()``` or ```WinJS.UI.executeTransition()``` as explained in https://msdn.microsoft.com/en-us/library/windows/apps/Dn127042(v=win.10).aspx#creating_custom_animations, *Combining custom animations and transitions* doesn't work either, I can see opacity change and element fading in, but no translation.

**Comment by rigdern** [comment]
Please provide an app/page which repros this bug. You can share it on OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

Also, we have some examples of how to use the [animation APIs on our Try Site](http://try.buildwinjs.com/#animations).

**Comment by ravindrakumarks** [comment]
looks like the transition with providing {top, left} started working without anything - weird why it wasn't.
However I still have issues with custom animation as described in the above link.

I used the Windows 8.1 code "HTML animation library sample". I modified transitionPages.js, instead of calling ```WinJS.UI.Animation.enterPage([[header, featureLabel], [inputLabel, input], [outputLabel, output, footer]], {top: "200px", left: "0px" })```, I substituted the function specified in the msdn help page mentioned above ```runCustomShowStoryboard()```.

I also tried setting ```from: { top: "200px", left: "0px" }``` and that didn't work either. I see only the opacity transition working and not the translate animation.

code@: https://onedrive.live.com/redir?resid=BE8342DF6C75658B!1618&authkey=!AASSkeYc5r2GadM&ithint=file%2c7z
(PS: Sorry for not cleaning up the code, didn't have too much time)

**Comment by ravindrakumarks** [comment]
tried with try.buildwinjs.com/#animations as well, and I see the same result
```
function runEnterPageAnimation() {
    // Get user selection from control
    var pageSections = document.getElementById("pageSectionsControl").value;
    document.querySelector(".box").style.overflow = "hidden";

    // Animate the application's entrance in the number of stages chosen by the user
    // Use the recommended offset by leaving the offset argument empty to get the best performance
    var enterPage;
    var rootGrid = document.getElementById("rootGrid");
    var pageContent = document.getElementById("pageContent");
    var header = document.querySelector("header");
    var footer = document.querySelector("footer");
    
    function runCustomShowStoryboard(target) {
        var promise1 = WinJS.UI.executeAnimation(
            target,
            {
                keyframe: "custom-translate-in",
                property: "transform",
                delay: 0,
                duration: 367,
                timing: "linear",
                from: {top:"50px", left: "0px"},
                to: {top:"0px", left: "0px"}
            });
        var promise2 = WinJS.UI.executeTransition(
            target,
            {
                property: "opacity",
                delay: 0,
                duration: 367,
                timing: "linear",
                from: 0,
                to: 1
            });
        return WinJS.Promise.join([promise1, promise2]);
    }
    switch (pageSections) {
        case "1":
            // Animate the whole page together
            enterPage = runCustomShowStoryboard(rootGrid, null);
            break;
        case "2":
            // Stagger the header and body
            enterPage = WinJS.UI.Animation.enterPage([header, [pageContent, footer]], null);
            break;
        case "3":
            // Stagger the header, input, and output areas
            enterPage = runCustomShowStoryboard([header, pageContent, footer]);
            break;
    }
    document.getElementById("message").textContent = "Page appeared in " + pageSections + " section(s).";
}
var runAnimation = document.getElementById("runAnimation");
runAnimation.addEventListener("click", runEnterPageAnimation, false);
```

**Comment by rigdern** [comment]
I tried the project you shared and was able to make a couple of changes to get it working. First of all, the animations are being applied only to the "Output" label which I didn't realize just by reading your description.

![image](https://cloud.githubusercontent.com/assets/199935/6679730/ae732b74-cc09-11e4-962b-13f85fca8eb8.png)

When running your project, neither of your animations played. Here's what I changed:

#### Opacity

The opacity wasn't specifying a `from` and because the opacity was already `1`, there was no need to animate `opacity`. Specifying `from` fixed this.

```js
var promise2 = WinJS.UI.executeTransition(
    target,
    {
        property: "opacity",
        delay: 0,
        duration: 167,
        timing: "linear",
        from: 0, // specify what the opacity should be animated from
        to: 1
    });
```

#### Transform
The transform specifies a keyframe but the keyframe wasn't specified in CSS. Specifying it fixes this.

Make sure `transitionPages.html` loads this CSS. I copied this from the MSDN example page you linked me to:

```css
@keyframes custom-translate-in {
    from {
        transform: translateY(50px);
    }
    to {
        transform: none;
    }
}
```

#### Miscellaneous

Because I've just described how to fix the VS project, I'm going to guess that you will be able to solve your problems from that description and I'm not going to look at the snippet you just posted carefully (but I can look at it if you need more help). But while glancing at it, I noticed one mistake in the notation that is passed to `from`/`to` in `executeAnimation`.

The values you pass here get written directly to the DOM element's style property. So for example, here you specified `property: "transform"` and `from: {top:"50px", left: "0px"}` so `executeAnimation` will try to do `element.style.transform = '{top: "50px", left: "0px"}';` which isn't meaningful to the DOM. Instead, you should specify the `from` as `translate(50px, 0px);` which is the proper notation for a DOM `style.transform`.

The `{ top: "50px", left: "0px" }` notation is used by certain built-in animation functions like [`enterPage`](https://msdn.microsoft.com/en-us/library/windows/apps/br212672.aspx) for their `offset` parameters. It is not used by `executeAnimation` or `executeTransition`.

**Comment by ravindrakumarks** [comment]
cool, thanks for clarifying, I guess the CSS part was one thing I missed, and from the initial looks thought it was either css or JS changes.

**Comment by PatrickSCLin** [comment]
Does Universal Window App on Desktop support customAnimation ?

I found duration of executeAnimation or executeTransition not really work on desktop but work fine on mobile simulator

**Comment by rigdern** [comment]
@PatrickSCLin Yes, `executeAnimation` and `executeTransition` are supported in Universal Windows Apps on desktop. In fact, they are supported in all environments that WinJS supports (UWAs and [browsers](https://github.com/winjs/winjs/wiki/Browser-Support))

If you've found a bug, please file a GitHub issue.

**Comment by PatrickSCLin** [comment]
don't need a specific file to reproduce this issue, 
just open the universal windows sample -> AnimationLibrary, edit CustomAnimation.js
the duration doesn't work when I choose to run as Local Machine (Windows 10) whatever I set the duration be 5ms or 5000ms,
the effect just be done immediately, but it works fine on mobile simulator
