### ISSUE TITLE
WinJS 3.0.1 support in Google Chrome for iOS 8 ?

### ISSUE THREAD

**Issue by greybax** [winjs/winjs#964]
Hi, I can't find any official documentation on WinJS support in chrome for iOS 7.
I could find out here https://github.com/winjs/winjs/wiki/Browser-Support 
that it's not supported for iOS 7, but there is no any unformation about iOS 8.
What is the current status? If it's not supported not, are you planning to add support in future?

**Comment by xirzec** [comment]
iOS 8 is certainly supported. I believe Chrome on iOS is also supported by default since it uses the same engine that Safari uses (which *is* supported.) 

Are there any bugs you are running into on this browser?

**Comment by rigdern** [comment]
@jayrenn Can you take care of fixing this? There are a couple of things we'd like to adjust:
  - In the table, replace iOS 7 with iOS 8.
  - Notice that there are many holes in the table that will never be filled because the combinations don't make sense (e.g. IE 10 on iOS). We want to get rid of all of these cells that don't make sense rather than making it look like we don't support them today but might someday. Perhaps we should put the table into a list instead?

**Comment by jayrenn** [comment]
Updated the browser support page.
