### ISSUE TITLE
Listview: expand an item on selection

### ISSUE THREAD

**Issue by pke** [winjs/winjs#978]
I wonder how difficult it is to expand an item in a listview when its selected (single select mode). Would that be done by CSS or with a special `itemInfo` so that the layout stays intact?
Basically my LV items have one line of display data, and when the user selects the item it should expand and reveal more detail in a second and third line.

PS:
I have the feeling I have asked that before here or somewhere else.

**Comment by rigdern** [comment]
What kind of layout are you using?

In `ListLayout` and `GridLayout`, all items must be the same size so that virtualization can work properly and quickly. Consequently there isn't a trivial solution in those layouts.

Here are some options:
  - If you are using `CellSpanningLayout`, just tell the ListView that the item has changed and return a new size when it calls `itemInfo`.
  - If you are using `ListLayout` and `GridLayout`, instead of making the item bigger you could add an item after the selected item to reveal the extra information. When selected, you can also change the styling on those two items to try to make them look like a single item.
  - If your collection is small, instead of a `ListView` you could try using a `Repeater` with `ItemContainer`s.

**Comment by pke** [comment]
I am using ListLayout and already thought about adding an item after the selected item with a custom renderer. I cannot use a `Repeater` because of the grouping I need.

**Comment by rigdern** [comment]
You could try simulating grouping using nested Repeaters.

Out of curiosity, I have a couple of questions for you about your scenario:
  - Approximately how large are the collections this ListView is handling?
  - Which ListView features are you using in this scenario? Editing animations, drag and drop, etc.

**Comment by pke** [comment]
>Approximately how large are the collections this ListView is handling?

The listview displays a schedule with no more than 100 entries, much less most of the time... around 30-50.

> Which ListView features are you using in this scenario? Editing animations, drag and drop, etc.

None, just invoke :)

**Comment by rigdern** [comment]
Because you're using less than 100 items, using a Repeater should be good. You can use nested Repeaters to simulate grouping and you can use the ItemContainer control to get the invoke visual. Does that help?

**Comment by pke** [comment]
I will try that when I have some spare time, yes. I'm starting to use more and more repeaters for simple lists, especially in my hub "home" pages. With 10 or less items, a listview is to heavy for such task, I guess.

**Comment by pke** [comment]
Just to clarify @rigdern how would using a Repeater help in this case? When an item is invoked I would  change that items template to reflect its selected and has additional controls in it?

**Comment by rigdern** [comment]
@pke Yes, that's exactly what I was thinking.

**Comment by pke** [comment]
I'll try that and report back here.
