### ISSUE TITLE
Why is WinJS.Application.sessionState not loaded when app terminated in VisualStudio?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#985]
The development cycle would be much for fluid if WinJS.Application.sessionState would not only be loaded for "terminated" apps. Why isn't it always loaded, regardless what the previous execution state was?

Terminating the app using "Suspend and Terminate" instead of "(Ctrl+)Shift+F5" is tiresome. Any tips?

**Comment by xirzec** [comment]
Setting aside the question of if this is desirable or not for a moment, I can offer some insights about why it is this way.

Essentially, the concern `WinJS.Application` is trying to mitigate is that if the user gets into a bad state that causes an appcrash that they can't get out of due to the app rehydrating into the bad state when they launch it again. The idea was that clearing the `sessionState` on non-normal termination would help them get back to a 'good' state where they could use the app again.

**Comment by pke** [comment]
Makes sense. What would u recommend for saving user settings in a way that they could also be edited by hand in a text editor? JSON saved in the local storage I guess?

**Comment by xirzec** [comment]
In the past I've manually saved to a JSON file in the user's appdata directory - there's even a helper for doing so: https://msdn.microsoft.com/en-us/library/windows/apps/hh700820.aspx

LocalStorage would also work, though you can't edit it externally and there are some (fairly generous) size limits.

**Comment by pke** [comment]
Yes thanks Jeff. With local storage I meant the app LocalStore, not HTML local storage. Sorry for the confusion.
