### ISSUE TITLE
ListView: Pressed down animation doesn't play with fast clicks

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#989]
When clicking on a ListView item for a very short period of time, the ListView item gets invoked but does not give any visual indication. The pressed down animation does not play.

@TheWrathOfConst has a fix.

**Comment by TheWrathOfConst** [comment]
The problem with this issue is that we're removing the transform on the item in `ItemEventsHandler_resetPressedContainer` with this line of code:
```js
this._site.pressedContainer.style[transformNames.scriptName] = "";
```

This was intended to clear the transform for drag and drop start, so that the dragged item wouldn't be tilted. In its current location, this transform clearing is overly aggressive, because it leads to the transform being removed when it should not. Instead, we should move this line of code to `ItemEventsHandler_onDragStart`
